## Transformación logaritmica para variables con mucho sesgo

Cargamos el mismo conjunto de datos previo a la estandarización y eliminamos las mismas variables que antes

In [2]:
import pandas as pd
from sklearn.cluster import KMeans
from kmodes.kprototypes import KPrototypes
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import unicodedata
import re
import gower

import kmedoids # Nueva librería para PAM
from sklearn.cluster import AgglomerativeClustering
from sklearn.mixture import GaussianMixture

from scipy.cluster.hierarchy import dendrogram, linkage
import scipy.spatial.distance as ssd
import prince
import numpy as np

from itertools import combinations
import heapq
from sklearn.preprocessing import StandardScaler

In [3]:
trainset = pd.read_csv("train_imputado.csv")

In [4]:
trainset.head(10)

,edad_an,tamano_hogar,psu,ratio_pobreza,tiempo_seg_cond1,tiempo_seg_cond2,tiempo_seg_cond3,tiempo_seg_cond4,pulso,peso_kg,...,elegibilidad_balance,convulsiones,caidas,fracturas,medicacion_osteoporosis,aprueba_cond4,tamano_manguito_pa,estado_elastografia,tipo_sonda_elasto,raza_etnia
0,46.0,5.0,2.0,4.62,15.0,15.0,30.0,30.0,66.0,111.6,...,1,0,0,0,0,1,4.0,1,b'XL',3.0
1,57.0,3.0,2.0,2.17,15.0,15.0,30.0,30.0,73.0,124.1,...,1,0,0,0,0,1,4.0,1,b'XL',3.0
2,48.0,3.0,2.0,5.00,15.0,15.0,30.0,30.0,67.0,89.3,...,0,0,0,1,0,1,4.0,1,b'M',3.0
3,40.0,5.0,1.0,3.11,15.0,15.0,30.0,30.0,81.0,81.9,...,1,0,0,0,0,1,3.0,1,b'M',2.0
4,66.0,3.0,2.0,3.47,15.0,15.0,30.0,8.0,103.0,77.4,...,1,0,0,0,0,0,3.0,1,b'M',6.0
5,27.0,2.0,1.0,5.00,15.0,15.0,30.0,30.0,69.0,50.8,...,1,0,0,0,0,1,3.0,1,b'M',7.0
6,69.0,1.0,1.0,2.43,15.0,15.0,30.0,30.0,50.0,86.4,...,1,0,0,0,0,1,4.0,1,b'XL',3.0
7,33.0,5.0,2.0,1.05,15.0,15.0,30.0,30.0,58.0,84.2,...,1,0,0,0,0,1,3.0,1,b'M',3.0
8,54.0,4.0,1.0,5.00,15.0,15.0,30.0,22.0,73.0,94.2,...,1,0,0,0,0,1,4.0,1,b'XL',3.0
9,40.0,1.0,1.0,5.00,15.0,15.0,30.0,2.0,51.0,66.5,...,1,0,0,0,0,0,3.0,1,b'M',3.0

In [5]:
# 1. Cargar diccionario



ruta_diccionario = "../data/Diccionario_TFM_CompletoMF.xlsx"
diccionario = pd.read_excel(ruta_diccionario)

def normalizar_texto(x):
    x = str(x).strip().lower()
    x = unicodedata.normalize("NFKD", x).encode("ascii", "ignore").decode("utf-8")
    return x

def limpiar_nombre(col):
    col = col.lower()
    col = col.replace(" ", "_")
    col = re.sub(r'[^a-z0-9_]', '', col)
    return col

diccionario["Tipo de Variable"] = diccionario["Tipo de Variable"].apply(normalizar_texto)

cols_categoricas = diccionario.loc[
    diccionario["Tipo de Variable"].str.contains("categ", na=False), "Qué es"
].tolist()
var_categoricas = [col for col in cols_categoricas if col in trainset.columns]

cols_numericas = diccionario.loc[
    diccionario["Tipo de Variable"].str.contains("num", na=False), "Qué es"
].tolist()
var_numericas = [col for col in cols_numericas if col in trainset.columns]

trainset[var_numericas] = trainset[var_numericas].astype('float64')
trainset[var_categoricas] = trainset[var_categoricas].astype('object')

print(f"Número de columnas categóricas: {len(var_categoricas)}")
print(var_categoricas)

print(f"Número de columnas numéricas: {len(var_numericas)}")
print(var_numericas)

Número de columnas categóricas: 16
['genero', 'periodo_examen', 'pais_nacimiento', 'toma_suplementos', 'toma_antiacidos', 'estado_examen_balance', 'elegibilidad_balance', 'convulsiones', 'caidas', 'fracturas', 'medicacion_osteoporosis', 'aprueba_cond4', 'tamano_manguito_pa', 'estado_elastografia', 'tipo_sonda_elasto', 'raza_etnia']
Número de columnas numéricas: 46
['edad_an', 'tamano_hogar', 'psu', 'ratio_pobreza', 'tiempo_seg_cond1', 'tiempo_seg_cond2', 'tiempo_seg_cond3', 'tiempo_seg_cond4', 'pulso', 'peso_kg', 'altura_cm', 'imc', 'largo_pierna_superior_cm', 'largo_brazo_superior_cm', 'medidas_validas_elasto', 'intentos_totales_elasto', 'rigidez_mediana_kpa', 'rigidez_iqr', 'ratio_iqr_mediana', 'cap_mediana_db_m', 'cap_iqr', 'albumina_orina_mg_l', 'creatinina_orina_umol_l', 'ratio_albumina_creatinina', 'peso_flebotomia', 'proteina_c_reactiva_mg_l', 'leucocitos_totales', 'linfocitos_abs', 'monocitos_abs', 'neutrofilos_abs', 'eosinofilos_abs', 'eritrocitos_totales', 'hemoglobina_g_dl', 'volumen_corpuscular_medio', 'conc_hemoglobina_media', 'ancho_distribucion_eritrocitos', 'plaquetas_totales', 'volumen_plaquetario_medio', 'trigliceridos_mmol_l', 'ldl_martin_mmol_l', 'hdl_mmol_l', 'plomo_sangre_umol_l', 'cadmio_sangre_nmol_l', 'mercurio_sangre_nmol_l', 'selenio_sangre_umol_l', 'manganeso_sangre_nmol_l']

eliminamos las mismas variables que en el apartado anterior

In [6]:
columnas_a_eliminar = ['tiempo_seg_cond1', 'tiempo_seg_cond2', 'tiempo_seg_cond3', 'peso_kg', 'albumina_orina_mg_l', 'neutrofilos_abs','rigidez_iqr', 'ratio_iqr_mediana','medidas_validas_elasto','intentos_totales_elasto','psu', 'cadmio_sangre_nmol_l', 'mercurio_sangre_nmol_l']

# Utilizamos el método .drop() especificando que queremos eliminar columnas
trainset = trainset.drop(columns=columnas_a_eliminar)
trainset.shape

(1919, 49)

In [7]:
var_num = trainset.select_dtypes(include=['number'])
var_num.shape

(1919, 33)

obtenemos el skew para cada variable: medida estadística que describe la falta de simetría en la distribución de tus datos alrededor de su media.

In [8]:
asimetria = var_num.skew().sort_values(ascending=False)

print("--- Nivel de Asimetría (Skewness) de las Variables ---")
print("Valores ideales: entre -1 y 1. Valores > 1 o < -1 indican asimetría severa.\n")
print(asimetria)

--- Nivel de Asimetría (Skewness) de las Variables ---
Valores ideales: entre -1 y 1. Valores > 1 o < -1 indican asimetría severa.

plomo_sangre_umol_l               19.482658
ratio_albumina_creatinina         14.215589
rigidez_mediana_kpa                7.974745
proteina_c_reactiva_mg_l           6.952438
trigliceridos_mmol_l               6.916607
eosinofilos_abs                    5.417549
selenio_sangre_umol_l              5.352683
ancho_distribucion_eritrocitos     5.211623
cap_iqr                            1.838814
peso_flebotomia                    1.829170
manganeso_sangre_nmol_l            1.501256
creatinina_orina_umol_l            1.216544
monocitos_abs                      1.209084
linfocitos_abs                     1.156344
imc                                1.138741
leucocitos_totales                 1.137664
hdl_mmol_l                         1.131395
tamano_hogar                       0.884210
plaquetas_totales                  0.787695
volumen_plaquetario_medio          0.648152
pulso                              0.533362
ldl_martin_mmol_l                  0.386823
eritrocitos_totales                0.346634
largo_brazo_superior_cm            0.163264
altura_cm                          0.147654
cap_mediana_db_m                   0.081952
largo_pierna_superior_cm           0.006313
ratio_pobreza                     -0.176222
hemoglobina_g_dl                  -0.242129
edad_an                           -0.293307
conc_hemoglobina_media            -0.387832
tiempo_seg_cond4                  -0.744717
volumen_corpuscular_medio         -0.815809
dtype: float64

se puede observar que para ciertas variables la transformación logaritmica no será sido del todo útil esto es debido a:

1. medidas como plomo_sangre_umol_l son muy pequeñas y la la función log1p(x) uma 1 antes de sacar el logaritmo por tanto si se le suma 1 a un valor muy pequeño es practicamnete 1.

Para estos valores se aplica la transformación de raiz cuadrada.

In [9]:
skew_actual = var_num.skew()
var_num_log = var_num.copy()

# 2. Filtrar las variables con asimetría severa
variables_sesgadas = skew_actual[skew_actual.abs() > 1].index.tolist()

print("--- VARIABLES DETECTADAS PARA TRANSFORMACIÓN ---")
for col in variables_sesgadas:
    print(f"- {col} (Skew original: {skew_actual[col]:.2f})")

# Definimos las variables rebeldes que necesitan raíz cuadrada en lugar de logaritmo
variables_raiz = ['plomo_sangre_umol_l']

print("\n--- APLICANDO TRANSFORMACIONES ---")
# 3. Aplicar la transformación (Logaritmo o Raíz Cuadrada)
for col in variables_sesgadas:
    # Si la variable está en nuestra lista de excepciones, aplicamos raíz cuadrada
    if col in variables_raiz:
        var_num_log[col] = np.sqrt(var_num_log[col])
        print(f"✓ Raíz cuadrada aplicada a: {col}")
    else:
        # Para el resto, verificamos que no haya valores negativos antes de aplicar el logaritmo
        if (var_num_log[col] < 0).any():
            print(f"⚠️ Advertencia: {col} tiene valores negativos. No se aplicó logaritmo.")
        else:
            var_num_log[col] = np.log1p(var_num_log[col])
            # print(f"✓ Logaritmo aplicado a: {col}") # Opcional: descomentar para ver el progreso

print("\nTransformaciones aplicadas con éxito.")

# 4. Verificar los nuevos niveles de asimetría para confirmar la mejora
print("\n--- NUEVA ASIMETRÍA TRAS LAS TRANSFORMACIONES ---")
skew_nuevo = var_num_log[variables_sesgadas].skew()
for col in variables_sesgadas:
    print(f"- {col} (Nuevo Skew: {skew_nuevo[col]:.2f})")

--- VARIABLES DETECTADAS PARA TRANSFORMACIÓN ---
- imc (Skew original: 1.14)
- rigidez_mediana_kpa (Skew original: 7.97)
- cap_iqr (Skew original: 1.84)
- creatinina_orina_umol_l (Skew original: 1.22)
- ratio_albumina_creatinina (Skew original: 14.22)
- peso_flebotomia (Skew original: 1.83)
- proteina_c_reactiva_mg_l (Skew original: 6.95)
- leucocitos_totales (Skew original: 1.14)
- linfocitos_abs (Skew original: 1.16)
- monocitos_abs (Skew original: 1.21)
- eosinofilos_abs (Skew original: 5.42)
- ancho_distribucion_eritrocitos (Skew original: 5.21)
- trigliceridos_mmol_l (Skew original: 6.92)
- hdl_mmol_l (Skew original: 1.13)
- plomo_sangre_umol_l (Skew original: 19.48)
- selenio_sangre_umol_l (Skew original: 5.35)
- manganeso_sangre_nmol_l (Skew original: 1.50)

--- APLICANDO TRANSFORMACIONES ---
✓ Raíz cuadrada aplicada a: plomo_sangre_umol_l

Transformaciones aplicadas con éxito.

--- NUEVA ASIMETRÍA TRAS LAS TRANSFORMACIONES ---
- imc (Nuevo Skew: 0.42)
- rigidez_mediana_kpa (Nuevo Skew: 2.00)
- cap_iqr (Nuevo Skew: -0.26)
- creatinina_orina_umol_l (Nuevo Skew: -0.72)
- ratio_albumina_creatinina (Nuevo Skew: 1.66)
- peso_flebotomia (Nuevo Skew: 0.10)
- proteina_c_reactiva_mg_l (Nuevo Skew: 1.02)
- leucocitos_totales (Nuevo Skew: 0.23)
- linfocitos_abs (Nuevo Skew: 0.22)
- monocitos_abs (Nuevo Skew: 0.72)
- eosinofilos_abs (Nuevo Skew: 2.57)
- ancho_distribucion_eritrocitos (Nuevo Skew: 2.85)
- trigliceridos_mmol_l (Nuevo Skew: 1.56)
- hdl_mmol_l (Nuevo Skew: 0.57)
- plomo_sangre_umol_l (Nuevo Skew: 4.32)
- selenio_sangre_umol_l (Nuevo Skew: 1.85)
- manganeso_sangre_nmol_l (Nuevo Skew: 0.27)

In [9]:
print("=" * 80)
print("FORWARD SELECTION CON TAMAÑO DE CLÚSTERES (N)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 20    # Límite máximo de variables a agrupar
columnas_totales = var_num_log.columns.tolist()

resultados_finales = {}
campeon_global_score = -1
campeon_global_k = -1
campeon_global_vars = []
campeon_global_conteos = []

for k in rango_k:
    print(f"\n[ Iniciando búsqueda para K={k} ]")

    columnas_disponibles = columnas_totales.copy()
    variables_seleccionadas = []

    # --- PASO 1: Buscar el mejor PAR inicial (La base sólida) ---
    mejor_score_par = -1
    mejor_par = ()
    mejor_labels_par = None

    # Probamos las parejas posibles
    for combo in combinations(columnas_disponibles, 2):
        X_subset = var_num_log[list(combo)]
        kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
        labels = kmeans.fit_predict(X_subset)
        score = silhouette_score(X_subset, labels)

        if score > mejor_score_par:
            mejor_score_par = score
            mejor_par = combo
            mejor_labels_par = labels # Guardamos las etiquetas ganadoras

    # Fijamos el mejor par y lo sacamos de las disponibles
    variables_seleccionadas.extend(mejor_par)
    for var in mejor_par:
        columnas_disponibles.remove(var)

    # Calculamos N por clúster
    conteos_par = np.bincount(mejor_labels_par).tolist()

    print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

    # Guardamos el historial de scores y conteos
    historial_scores = [mejor_score_par]
    historial_conteos = [conteos_par]

    # --- PASO 2: Forward Selection (Añadir 1 a 1 hasta max_variables) ---
    for paso in range(3, max_variables + 1):
        mejor_score_paso = -1
        mejor_variable_paso = None
        mejor_labels_paso = None

        # Probamos a añadir cada una de las variables que quedan libres
        for var_candidata in columnas_disponibles:
            features_a_probar = variables_seleccionadas + [var_candidata]
            X_subset = var_num_log[features_a_probar]

            kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
            labels = kmeans.fit_predict(X_subset)
            score = silhouette_score(X_subset, labels)

            if score > mejor_score_paso:
                mejor_score_paso = score
                mejor_variable_paso = var_candidata
                mejor_labels_paso = labels # Guardamos las etiquetas ganadoras

        # Consolidamos la variable ganadora de este paso
        variables_seleccionadas.append(mejor_variable_paso)
        columnas_disponibles.remove(mejor_variable_paso)

        # Calculamos N por clúster
        conteos_paso = np.bincount(mejor_labels_paso).tolist()

        historial_scores.append(mejor_score_paso)
        historial_conteos.append(conteos_paso)

        print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

    # --- PASO 3: Encontrar el pico máximo para este K ---
    indice_mejor_momento = historial_scores.index(max(historial_scores))
    score_pico = historial_scores[indice_mejor_momento]
    conteos_pico = historial_conteos[indice_mejor_momento]

    # El índice 0 equivale a 2 variables, índice 1 a 3 variables, etc.
    vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

    resultados_finales[k] = {
        'score': score_pico,
        'variables': vars_en_pico,
        'conteos': conteos_pico
    }

    # Actualizar campeón global absoluto
    if score_pico > campeon_global_score:
        campeon_global_score = score_pico
        campeon_global_k = k
        campeon_global_vars = vars_en_pico
        campeon_global_conteos = conteos_pico

print("\n" + "=" * 80)
print("🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆")
print("=" * 80)

print(f"\n🌟 EL CAMPEÓN ABSOLUTO:")
print(f"  -> K Óptimo: {campeon_global_k}")
print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
print(f"  -> Distribución de Pacientes (N): {campeon_global_conteos}")
print(f"  -> Variables óptimas ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

print("\n--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---")
for k in rango_k:
    res = resultados_finales[k]
    print(f"\nPara K={k}:")
    print(f"  -> Silhouette Score: {res['score']:.4f}")
    print(f"  -> Distribución de Pacientes (N): {res['conteos']}")
    print(f"  -> N Variables: {len(res['variables'])}")
    print(f"  -> Variables: {', '.join(res['variables'])}")

================================================================================
FORWARD SELECTION CON TAMAÑO DE CLÚSTERES (N)
================================================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'plomo_sangre_umol_l') (Score: 0.7826) | Tamaños N: [1250, 669]
  -> + Variable 3: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.7816 | Tamaños N: [1250, 669]
  -> + Variable 4: 'selenio_sangre_umol_l' | Nuevo Score: 0.7805 | Tamaños N: [1250, 669]
  -> + Variable 5: 'eosinofilos_abs' | Nuevo Score: 0.7795 | Tamaños N: [1250, 669]
  -> + Variable 6: 'monocitos_abs' | Nuevo Score: 0.7785 | Tamaños N: [1250, 669]
  -> + Variable 7: 'hdl_mmol_l' | Nuevo Score: 0.7770 | Tamaños N: [1250, 669]
  -> + Variable 8: 'linfocitos_abs' | Nuevo Score: 0.7748 | Tamaños N: [1250, 669]
  -> + Variable 9: 'imc' | Nuevo Score: 0.7727 | Tamaños N: [1250, 669]
  -> + Variable 10: 'leucocitos_totales' | Nuevo Score: 0.7704 | Tamaños N: [1250, 669]
  -> + Variable 11: 'trigliceridos_mmol_l' | Nuevo Score: 0.7675 | Tamaños N: [1250, 669]
  -> + Variable 12: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.7643 | Tamaños N: [1250, 669]
  -> + Variable 13: 'rigidez_mediana_kpa' | Nuevo Score: 0.7613 | Tamaños N: [1250, 669]
  -> + Variable 14: 'eritrocitos_totales' | Nuevo Score: 0.7564 | Tamaños N: [1250, 669]
  -> + Variable 15: 'cap_iqr' | Nuevo Score: 0.7511 | Tamaños N: [1250, 669]
  -> + Variable 16: 'peso_flebotomia' | Nuevo Score: 0.7434 | Tamaños N: [1250, 669]
  -> + Variable 17: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.7352 | Tamaños N: [1250, 669]
  -> + Variable 18: 'creatinina_orina_umol_l' | Nuevo Score: 0.7269 | Tamaños N: [1250, 669]
  -> + Variable 19: 'conc_hemoglobina_media' | Nuevo Score: 0.7183 | Tamaños N: [1250, 669]
  -> + Variable 20: 'ldl_martin_mmol_l' | Nuevo Score: 0.7099 | Tamaños N: [1250, 669]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'plomo_sangre_umol_l') (Score: 0.8004) | Tamaños N: [1074, 473, 372]
  -> + Variable 3: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.7983 | Tamaños N: [1074, 473, 372]
  -> + Variable 4: 'selenio_sangre_umol_l' | Nuevo Score: 0.7958 | Tamaños N: [1074, 473, 372]
  -> + Variable 5: 'eosinofilos_abs' | Nuevo Score: 0.7934 | Tamaños N: [1075, 473, 371]
  -> + Variable 6: 'monocitos_abs' | Nuevo Score: 0.7913 | Tamaños N: [1075, 473, 371]
  -> + Variable 7: 'hdl_mmol_l' | Nuevo Score: 0.7880 | Tamaños N: [1075, 473, 371]
  -> + Variable 8: 'linfocitos_abs' | Nuevo Score: 0.7831 | Tamaños N: [1075, 473, 371]
  -> + Variable 9: 'imc' | Nuevo Score: 0.7784 | Tamaños N: [1075, 473, 371]
  -> + Variable 10: 'leucocitos_totales' | Nuevo Score: 0.7733 | Tamaños N: [1076, 473, 370]
  -> + Variable 11: 'trigliceridos_mmol_l' | Nuevo Score: 0.7670 | Tamaños N: [1076, 473, 370]
  -> + Variable 12: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.7600 | Tamaños N: [1076, 473, 370]
  -> + Variable 13: 'rigidez_mediana_kpa' | Nuevo Score: 0.7534 | Tamaños N: [1076, 473, 370]
  -> + Variable 14: 'eritrocitos_totales' | Nuevo Score: 0.7429 | Tamaños N: [1076, 473, 370]
  -> + Variable 15: 'cap_iqr' | Nuevo Score: 0.7319 | Tamaños N: [1076, 473, 370]
  -> + Variable 16: 'peso_flebotomia' | Nuevo Score: 0.7152 | Tamaños N: [1061, 496, 362]
  -> + Variable 17: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.6979 | Tamaños N: [1060, 496, 363]
  -> + Variable 18: 'creatinina_orina_umol_l' | Nuevo Score: 0.6804 | Tamaños N: [1060, 496, 363]
  -> + Variable 19: 'ratio_albumina_creatinina' | Nuevo Score: 0.6633 | Tamaños N: [1092, 473, 354]
  -> + Variable 20: 'conc_hemoglobina_media' | Nuevo Score: 0.6484 | Tamaños N: [1097, 473, 349]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'plomo_sangre_umol_l') (Score: 0.8174) | Tamaños N: [1022, 452, 242, 203]
  -> + Variable 3: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.8136 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 4: 'selenio_sangre_umol_l' | Nuevo Score: 0.8093 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 5: 'eosinofilos_abs' | Nuevo Score: 0.8055 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 6: 'monocitos_abs' | Nuevo Score: 0.8019 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 7: 'hdl_mmol_l' | Nuevo Score: 0.7963 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 8: 'linfocitos_abs' | Nuevo Score: 0.7880 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 9: 'imc' | Nuevo Score: 0.7799 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 10: 'leucocitos_totales' | Nuevo Score: 0.7714 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 11: 'trigliceridos_mmol_l' | Nuevo Score: 0.7607 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 12: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.7488 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 13: 'rigidez_mediana_kpa' | Nuevo Score: 0.7378 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 14: 'eritrocitos_totales' | Nuevo Score: 0.7203 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 15: 'cap_iqr' | Nuevo Score: 0.7022 | Tamaños N: [1022, 452, 241, 204]
  -> + Variable 16: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.6640 | Tamaños N: [1028, 401, 245, 245]
  -> + Variable 17: 'peso_flebotomia' | Nuevo Score: 0.6433 | Tamaños N: [1028, 401, 243, 247]
  -> + Variable 18: 'conc_hemoglobina_media' | Nuevo Score: 0.6211 | Tamaños N: [203, 452, 242, 1022]
  -> + Variable 19: 'creatinina_orina_umol_l' | Nuevo Score: 0.5996 | Tamaños N: [1022, 435, 226, 236]
  -> + Variable 20: 'ldl_martin_mmol_l' | Nuevo Score: 0.5742 | Tamaños N: [1022, 452, 242, 203]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tamano_hogar', 'plomo_sangre_umol_l') (Score: 0.8685) | Tamaños N: [329, 651, 230, 413, 296]
  -> + Variable 3: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.8272 | Tamaños N: [329, 413, 230, 651, 296]
  -> + Variable 4: 'selenio_sangre_umol_l' | Nuevo Score: 0.7809 | Tamaños N: [329, 413, 230, 651, 296]
  -> + Variable 5: 'eosinofilos_abs' | Nuevo Score: 0.7427 | Tamaños N: [329, 413, 230, 651, 296]
  -> + Variable 6: 'monocitos_abs' | Nuevo Score: 0.7049 | Tamaños N: [329, 413, 230, 651, 296]
  -> + Variable 7: 'hdl_mmol_l' | Nuevo Score: 0.6500 | Tamaños N: [329, 651, 230, 413, 296]
  -> + Variable 8: 'tiempo_seg_cond4' | Nuevo Score: 0.6394 | Tamaños N: [1022, 334, 210, 172, 181]
  -> + Variable 9: 'linfocitos_abs' | Nuevo Score: 0.6352 | Tamaños N: [1022, 334, 210, 172, 181]
  -> + Variable 10: 'imc' | Nuevo Score: 0.6310 | Tamaños N: [1022, 334, 210, 172, 181]
  -> + Variable 11: 'leucocitos_totales' | Nuevo Score: 0.6262 | Tamaños N: [1022, 334, 210, 172, 181]
  -> + Variable 12: 'trigliceridos_mmol_l' | Nuevo Score: 0.6194 | Tamaños N: [1022, 334, 210, 172, 181]
  -> + Variable 13: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.6119 | Tamaños N: [1022, 334, 210, 172, 181]
  -> + Variable 14: 'rigidez_mediana_kpa' | Nuevo Score: 0.6041 | Tamaños N: [1022, 334, 210, 172, 181]
  -> + Variable 15: 'eritrocitos_totales' | Nuevo Score: 0.5915 | Tamaños N: [1022, 334, 210, 172, 181]
  -> + Variable 16: 'cap_iqr' | Nuevo Score: 0.5742 | Tamaños N: [1022, 209, 213, 188, 287]
  -> + Variable 17: 'peso_flebotomia' | Nuevo Score: 0.5542 | Tamaños N: [1022, 209, 214, 187, 287]
  -> + Variable 18: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.5360 | Tamaños N: [1022, 334, 212, 172, 179]
  -> + Variable 19: 'conc_hemoglobina_media' | Nuevo Score: 0.5084 | Tamaños N: [1022, 209, 214, 187, 287]
  -> + Variable 20: 'creatinina_orina_umol_l' | Nuevo Score: 0.4889 | Tamaños N: [1022, 209, 214, 187, 287]

================================================================================
🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆
================================================================================

🌟 EL CAMPEÓN ABSOLUTO:
  -> K Óptimo: 5
  -> Silhouette Score Máximo: 0.8685
  -> Distribución de Pacientes (N): [329, 651, 230, 413, 296]
  -> Variables óptimas (2): tamano_hogar, plomo_sangre_umol_l

--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---

Para K=2:
  -> Silhouette Score: 0.7826
  -> Distribución de Pacientes (N): [1250, 669]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, plomo_sangre_umol_l

Para K=3:
  -> Silhouette Score: 0.8004
  -> Distribución de Pacientes (N): [1074, 473, 372]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, plomo_sangre_umol_l

Para K=4:
  -> Silhouette Score: 0.8174
  -> Distribución de Pacientes (N): [1022, 452, 242, 203]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, plomo_sangre_umol_l

Para K=5:
  -> Silhouette Score: 0.8685
  -> Distribución de Pacientes (N): [329, 651, 230, 413, 296]
  -> N Variables: 2
  -> Variables: tamano_hogar, plomo_sangre_umol_l

Los resultados del anterior clustering aunque prometedores NO SON VALIDOS ya que los datos han de , tener escalas similares. Para ello no se va a realiazr sobre los siguientes grupos:

Grupo 1: Escalas Altas (Medias entre 8 y 35)
Estas variables dominan por completo el cálculo de distancias actualmente. Sus valores suelen oscilar entre 5 y 40.

* conc_hemoglobina_media (Rango: 28.4 - 37.7)

* tiempo_seg_cond4 (Rango: 1.0 - 30.0)

* hemoglobina_g_dl (Rango: 8.1 - 18.6)

* peso_flebotomia (Rango: 8.7 - 12.4)

* volumen_plaquetario_medio (Rango: 5.9 - 12.5)

Grupo 2: Escalas Medias (Medias entre 1 y 5)
Este es el grupo más numeroso. Sus valores están contenidos principalmente entre el 0.5 y el 8.0.

* eritrocitos_totales

* cap_iqr

* ldl_martin_mmol_l

* tamano_hogar

* ancho_distribucion_eritrocitos

* ratio_albumina_creatinina

* rigidez_mediana_kpa

* proteina_c_reactiva_mg_l

* selenio_sangre_umol_l

* linfocitos_abs

Grupo 3: Escalas Bajas o Trazas (Medias menores a 1)
Estas variables son prácticamente invisibles para el algoritmo de clustering si se mezclan con el Grupo 1.

* hdl_mmol_l (Rango: 0.46 - 1.48)

* trigliceridos_mmol_l (Rango: 0.25 - 3.03)

* monocitos_abs (Rango: 0.10 - 0.99)

* eosinofilos_abs (Rango: 0.10 - 1.36)

* plomo_sangre_umol_l (Rango: 0.005 - 1.20)

USANDO K-MEANS

In [10]:
# 1. Definición de los grupos de variables por escala
grupos_escalas = {
    "Grupo 1 (Escalas Altas)": [
        'conc_hemoglobina_media', 'tiempo_seg_cond4', 'hemoglobina_g_dl',
        'peso_flebotomia', 'volumen_plaquetario_medio'
    ],
    "Grupo 2 (Escalas Medias)": [
        'eritrocitos_totales', 'cap_iqr', 'ldl_martin_mmol_l', 'tamano_hogar',
        'ancho_distribucion_eritrocitos', 'ratio_albumina_creatinina',
        'rigidez_mediana_kpa', 'proteina_c_reactiva_mg_l', 'selenio_sangre_umol_l',
        'linfocitos_abs'
    ],
    "Grupo 3 (Escalas Bajas)": [
        'hdl_mmol_l', 'trigliceridos_mmol_l', 'monocitos_abs',
        'eosinofilos_abs', 'plomo_sangre_umol_l'
    ]
}

print("=" * 80)
print("FORWARD SELECTION POR GRUPOS DE ESCALAS")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 20    # Límite máximo general (se ajustará por grupo)

# Iteramos sobre cada grupo de variables
for nombre_grupo, variables_grupo in grupos_escalas.items():
    print("\n" + "=" * 60)
    print(f"🚀 INICIANDO ANÁLISIS PARA: {nombre_grupo}")
    print("=" * 60)

    # Filtrar solo las columnas de var_num_log que existen en el grupo
    columnas_totales_grupo = [col for col in variables_grupo if col in var_num_log.columns]

    # Ajustar el máximo de variables a iterar al tamaño real del grupo
    max_vars_grupo = min(max_variables, len(columnas_totales_grupo))

    if max_vars_grupo < 2:
        print(f"⚠️ El {nombre_grupo} tiene menos de 2 variables disponibles. Saltando...")
        continue

    resultados_finales = {}
    campeon_global_score = -1
    campeon_global_k = -1
    campeon_global_vars = []
    campeon_global_conteos = []

    for k in rango_k:
        print(f"\n[ Iniciando búsqueda para K={k} ]")

        columnas_disponibles = columnas_totales_grupo.copy()
        variables_seleccionadas = []

        # --- PASO 1: Buscar el mejor PAR inicial ---
        mejor_score_par = -1
        mejor_par = ()
        mejor_labels_par = None

        for combo in combinations(columnas_disponibles, 2):
            X_subset = var_num_log[list(combo)]
            kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
            labels = kmeans.fit_predict(X_subset)
            score = silhouette_score(X_subset, labels)

            if score > mejor_score_par:
                mejor_score_par = score
                mejor_par = combo
                mejor_labels_par = labels

        # Consolidar el mejor par
        variables_seleccionadas.extend(mejor_par)
        for var in mejor_par:
            columnas_disponibles.remove(var)

        conteos_par = np.bincount(mejor_labels_par).tolist()

        print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

        historial_scores = [mejor_score_par]
        historial_conteos = [conteos_par]

        # --- PASO 2: Forward Selection ---
        for paso in range(3, max_vars_grupo + 1):
            mejor_score_paso = -1
            mejor_variable_paso = None
            mejor_labels_paso = None

            for var_candidata in columnas_disponibles:
                features_a_probar = variables_seleccionadas + [var_candidata]
                X_subset = var_num_log[features_a_probar]

                kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
                labels = kmeans.fit_predict(X_subset)
                score = silhouette_score(X_subset, labels)

                if score > mejor_score_paso:
                    mejor_score_paso = score
                    mejor_variable_paso = var_candidata
                    mejor_labels_paso = labels

            # Consolidar variable ganadora
            variables_seleccionadas.append(mejor_variable_paso)
            columnas_disponibles.remove(mejor_variable_paso)

            conteos_paso = np.bincount(mejor_labels_paso).tolist()

            historial_scores.append(mejor_score_paso)
            historial_conteos.append(conteos_paso)

            print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

        # --- PASO 3: Encontrar el pico máximo ---
        indice_mejor_momento = historial_scores.index(max(historial_scores))
        score_pico = historial_scores[indice_mejor_momento]
        conteos_pico = historial_conteos[indice_mejor_momento]

        vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

        resultados_finales[k] = {
            'score': score_pico,
            'variables': vars_en_pico,
            'conteos': conteos_pico
        }

        if score_pico > campeon_global_score:
            campeon_global_score = score_pico
            campeon_global_k = k
            campeon_global_vars = vars_en_pico
            campeon_global_conteos = conteos_pico

    # Imprimir resumen final por grupo
    print("\n" + "-" * 60)
    print(f"🏆 RESULTADOS: {nombre_grupo} 🏆")
    print("-" * 60)
    print(f"🌟 EL CAMPEÓN DEL GRUPO:")
    print(f"  -> K Óptimo: {campeon_global_k}")
    print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
    print(f"  -> Distribución (N): {campeon_global_conteos}")
    print(f"  -> Variables ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

================================================================================
FORWARD SELECTION POR GRUPOS DE ESCALAS
================================================================================

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 1 (Escalas Altas)
============================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7662) | Tamaños N: [1250, 669]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.7510 | Tamaños N: [1250, 669]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.7379 | Tamaños N: [1250, 669]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.7147 | Tamaños N: [1250, 669]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7641) | Tamaños N: [1076, 473, 370]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.7322 | Tamaños N: [1061, 496, 362]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.7035 | Tamaños N: [1060, 496, 363]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.6559 | Tamaños N: [1061, 496, 362]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7566) | Tamaños N: [1022, 452, 242, 203]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.7033 | Tamaños N: [1022, 452, 242, 203]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.6523 | Tamaños N: [1028, 401, 243, 247]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.5874 | Tamaños N: [1028, 401, 243, 247]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7382) | Tamaños N: [1022, 334, 205, 186, 172]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.6759 | Tamaños N: [1022, 334, 204, 187, 172]
  -> + Variable 4: 'hemoglobina_g_dl' | Nuevo Score: 0.4116 | Tamaños N: [523, 401, 243, 505, 247]
  -> + Variable 5: 'volumen_plaquetario_medio' | Nuevo Score: 0.3679 | Tamaños N: [490, 401, 243, 247, 538]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 1 (Escalas Altas) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 2
  -> Silhouette Score Máximo: 0.7662
  -> Distribución (N): [1250, 669]
  -> Variables (2): tiempo_seg_cond4, peso_flebotomia

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 2 (Escalas Medias)
============================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'ratio_albumina_creatinina') (Score: 0.6561) | Tamaños N: [1622, 297]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.6473 | Tamaños N: [1625, 294]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.6147 | Tamaños N: [1622, 297]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.5655 | Tamaños N: [1624, 295]
  -> + Variable 6: 'eritrocitos_totales' | Nuevo Score: 0.4996 | Tamaños N: [1623, 296]
  -> + Variable 7: 'cap_iqr' | Nuevo Score: 0.4476 | Tamaños N: [1635, 284]
  -> + Variable 8: 'tamano_hogar' | Nuevo Score: 0.3963 | Tamaños N: [1393, 526]
  -> + Variable 9: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.3002 | Tamaños N: [855, 1064]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.2563 | Tamaños N: [855, 1064]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tamano_hogar', 'ancho_distribucion_eritrocitos') (Score: 0.6791) | Tamaños N: [625, 1064, 230]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.6431 | Tamaños N: [526, 980, 413]
  -> + Variable 4: 'rigidez_mediana_kpa' | Nuevo Score: 0.5226 | Tamaños N: [980, 413, 526]
  -> + Variable 5: 'ratio_albumina_creatinina' | Nuevo Score: 0.4334 | Tamaños N: [785, 949, 185]
  -> + Variable 6: 'linfocitos_abs' | Nuevo Score: 0.4452 | Tamaños N: [1221, 197, 501]
  -> + Variable 7: 'eritrocitos_totales' | Nuevo Score: 0.4095 | Tamaños N: [1221, 197, 501]
  -> + Variable 8: 'cap_iqr' | Nuevo Score: 0.3527 | Tamaños N: [785, 953, 181]
  -> + Variable 9: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.3016 | Tamaños N: [793, 192, 934]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.2786 | Tamaños N: [497, 1209, 213]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tamano_hogar', 'ancho_distribucion_eritrocitos') (Score: 0.7698) | Tamaños N: [625, 651, 230, 413]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.7231 | Tamaños N: [625, 651, 413, 230]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.5621 | Tamaños N: [329, 1064, 429, 97]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.4602 | Tamaños N: [329, 1064, 296, 230]
  -> + Variable 6: 'ratio_albumina_creatinina' | Nuevo Score: 0.3977 | Tamaños N: [569, 174, 225, 951]
  -> + Variable 7: 'eritrocitos_totales' | Nuevo Score: 0.3500 | Tamaños N: [569, 173, 225, 952]
  -> + Variable 8: 'cap_iqr' | Nuevo Score: 0.2581 | Tamaños N: [501, 385, 165, 868]
  -> + Variable 9: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.2524 | Tamaños N: [563, 197, 934, 225]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.2027 | Tamaños N: [566, 937, 191, 225]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tamano_hogar', 'ancho_distribucion_eritrocitos') (Score: 0.8684) | Tamaños N: [329, 651, 230, 413, 296]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.7865 | Tamaños N: [329, 651, 413, 97, 429]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.6674 | Tamaños N: [329, 651, 429, 97, 413]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.4827 | Tamaños N: [329, 1064, 296, 97, 133]
  -> + Variable 6: 'eritrocitos_totales' | Nuevo Score: 0.3814 | Tamaños N: [329, 651, 429, 97, 413]
  -> + Variable 7: 'cap_iqr' | Nuevo Score: 0.2886 | Tamaños N: [329, 651, 413, 97, 429]
  -> + Variable 8: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.2179 | Tamaños N: [295, 581, 328, 485, 230]
  -> + Variable 9: 'ratio_albumina_creatinina' | Nuevo Score: 0.2183 | Tamaños N: [546, 669, 322, 225, 157]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.1706 | Tamaños N: [551, 541, 441, 225, 161]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 2 (Escalas Medias) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 5
  -> Silhouette Score Máximo: 0.8684
  -> Distribución (N): [329, 651, 230, 413, 296]
  -> Variables (2): tamano_hogar, ancho_distribucion_eritrocitos

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 3 (Escalas Bajas)
============================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('trigliceridos_mmol_l', 'plomo_sangre_umol_l') (Score: 0.5418) | Tamaños N: [542, 1377]
  -> + Variable 3: 'eosinofilos_abs' | Nuevo Score: 0.4942 | Tamaños N: [515, 1404]
  -> + Variable 4: 'monocitos_abs' | Nuevo Score: 0.4413 | Tamaños N: [543, 1376]
  -> + Variable 5: 'hdl_mmol_l' | Nuevo Score: 0.3866 | Tamaños N: [574, 1345]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('trigliceridos_mmol_l', 'plomo_sangre_umol_l') (Score: 0.4683) | Tamaños N: [780, 925, 214]
  -> + Variable 3: 'eosinofilos_abs' | Nuevo Score: 0.3940 | Tamaños N: [782, 925, 212]
  -> + Variable 4: 'monocitos_abs' | Nuevo Score: 0.3270 | Tamaños N: [245, 877, 797]
  -> + Variable 5: 'hdl_mmol_l' | Nuevo Score: 0.2779 | Tamaños N: [251, 887, 781]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('trigliceridos_mmol_l', 'plomo_sangre_umol_l') (Score: 0.4386) | Tamaños N: [399, 674, 85, 761]
  -> + Variable 3: 'eosinofilos_abs' | Nuevo Score: 0.3772 | Tamaños N: [778, 816, 289, 36]
  -> + Variable 4: 'monocitos_abs' | Nuevo Score: 0.2831 | Tamaños N: [389, 679, 771, 80]
  -> + Variable 5: 'hdl_mmol_l' | Nuevo Score: 0.2270 | Tamaños N: [90, 675, 409, 745]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('eosinofilos_abs', 'plomo_sangre_umol_l') (Score: 0.4185) | Tamaños N: [735, 702, 377, 88, 17]
  -> + Variable 3: 'trigliceridos_mmol_l' | Nuevo Score: 0.3674 | Tamaños N: [675, 744, 275, 36, 189]
  -> + Variable 4: 'hdl_mmol_l' | Nuevo Score: 0.2498 | Tamaños N: [315, 517, 351, 664, 72]
  -> + Variable 5: 'monocitos_abs' | Nuevo Score: 0.2096 | Tamaños N: [74, 352, 663, 508, 322]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 3 (Escalas Bajas) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 2
  -> Silhouette Score Máximo: 0.5418
  -> Distribución (N): [542, 1377]
  -> Variables (2): trigliceridos_mmol_l, plomo_sangre_umol_l

Usando Clustering Jerarquico

In [11]:


# 1. Definición de los grupos de variables por escala
grupos_escalas = {
    "Grupo 1 (Escalas Altas)": [
        'conc_hemoglobina_media', 'tiempo_seg_cond4', 'hemoglobina_g_dl',
        'peso_flebotomia', 'volumen_plaquetario_medio'
    ],
    "Grupo 2 (Escalas Medias)": [
        'eritrocitos_totales', 'cap_iqr', 'ldl_martin_mmol_l', 'tamano_hogar',
        'ancho_distribucion_eritrocitos', 'ratio_albumina_creatinina',
        'rigidez_mediana_kpa', 'proteina_c_reactiva_mg_l', 'selenio_sangre_umol_l',
        'linfocitos_abs'
    ],
    "Grupo 3 (Escalas Bajas)": [
        'hdl_mmol_l', 'trigliceridos_mmol_l', 'monocitos_abs',
        'eosinofilos_abs', 'plomo_sangre_umol_l'
    ]
}

print("=" * 80)
print("FORWARD SELECTION POR GRUPOS DE ESCALAS (CLUSTERING JERÁRQUICO)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 20    # Límite máximo general (se ajustará por grupo)

# Iteramos sobre cada grupo de variables
for nombre_grupo, variables_grupo in grupos_escalas.items():
    print("\n" + "=" * 60)
    print(f"🚀 INICIANDO ANÁLISIS PARA: {nombre_grupo}")
    print("=" * 60)

    # Filtrar solo las columnas de var_num_log que existen en el grupo
    columnas_totales_grupo = [col for col in variables_grupo if col in var_num_log.columns]

    # Ajustar el máximo de variables a iterar al tamaño real del grupo
    max_vars_grupo = min(max_variables, len(columnas_totales_grupo))

    if max_vars_grupo < 2:
        print(f"⚠️ El {nombre_grupo} tiene menos de 2 variables disponibles. Saltando...")
        continue

    resultados_finales = {}
    campeon_global_score = -1
    campeon_global_k = -1
    campeon_global_vars = []
    campeon_global_conteos = []

    for k in rango_k:
        print(f"\n[ Iniciando búsqueda para K={k} ]")

        columnas_disponibles = columnas_totales_grupo.copy()
        variables_seleccionadas = []

        # --- PASO 1: Buscar el mejor PAR inicial ---
        mejor_score_par = -1
        mejor_par = ()
        mejor_labels_par = None

        for combo in combinations(columnas_disponibles, 2):
            X_subset = var_num_log[list(combo)]

            # Instanciamos y ajustamos Clustering Jerárquico
            hclust = AgglomerativeClustering(n_clusters=k)
            labels = hclust.fit_predict(X_subset)

            score = silhouette_score(X_subset, labels)

            if score > mejor_score_par:
                mejor_score_par = score
                mejor_par = combo
                mejor_labels_par = labels

        # Consolidar el mejor par
        variables_seleccionadas.extend(mejor_par)
        for var in mejor_par:
            columnas_disponibles.remove(var)

        conteos_par = np.bincount(mejor_labels_par).tolist()

        print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

        historial_scores = [mejor_score_par]
        historial_conteos = [conteos_par]

        # --- PASO 2: Forward Selection ---
        for paso in range(3, max_vars_grupo + 1):
            mejor_score_paso = -1
            mejor_variable_paso = None
            mejor_labels_paso = None

            for var_candidata in columnas_disponibles:
                features_a_probar = variables_seleccionadas + [var_candidata]
                X_subset = var_num_log[features_a_probar]

                # Instanciamos y ajustamos Clustering Jerárquico
                hclust = AgglomerativeClustering(n_clusters=k)
                labels = hclust.fit_predict(X_subset)

                score = silhouette_score(X_subset, labels)

                if score > mejor_score_paso:
                    mejor_score_paso = score
                    mejor_variable_paso = var_candidata
                    mejor_labels_paso = labels

            # Consolidar variable ganadora
            variables_seleccionadas.append(mejor_variable_paso)
            columnas_disponibles.remove(mejor_variable_paso)

            conteos_paso = np.bincount(mejor_labels_paso).tolist()

            historial_scores.append(mejor_score_paso)
            historial_conteos.append(conteos_paso)

            print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

        # --- PASO 3: Encontrar el pico máximo ---
        indice_mejor_momento = historial_scores.index(max(historial_scores))
        score_pico = historial_scores[indice_mejor_momento]
        conteos_pico = historial_conteos[indice_mejor_momento]

        vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

        resultados_finales[k] = {
            'score': score_pico,
            'variables': vars_en_pico,
            'conteos': conteos_pico
        }

        if score_pico > campeon_global_score:
            campeon_global_score = score_pico
            campeon_global_k = k
            campeon_global_vars = vars_en_pico
            campeon_global_conteos = conteos_pico

    # Imprimir resumen final por grupo
    print("\n" + "-" * 60)
    print(f"🏆 RESULTADOS: {nombre_grupo} 🏆")
    print("-" * 60)
    print(f"🌟 EL CAMPEÓN DEL GRUPO:")
    print(f"  -> K Óptimo: {campeon_global_k}")
    print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
    print(f"  -> Distribución (N): {campeon_global_conteos}")
    print(f"  -> Variables ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

================================================================================
FORWARD SELECTION POR GRUPOS DE ESCALAS (CLUSTERING JERÁRQUICO)
================================================================================

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 1 (Escalas Altas)
============================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7333) | Tamaños N: [1423, 496]
  -> + Variable 3: 'hemoglobina_g_dl' | Nuevo Score: 0.7120 | Tamaños N: [1405, 514]
  -> + Variable 4: 'conc_hemoglobina_media' | Nuevo Score: 0.7031 | Tamaños N: [1406, 513]
  -> + Variable 5: 'volumen_plaquetario_medio' | Nuevo Score: 0.6857 | Tamaños N: [1428, 491]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7692) | Tamaños N: [395, 496, 1028]
  -> + Variable 3: 'volumen_plaquetario_medio' | Nuevo Score: 0.7157 | Tamaños N: [456, 435, 1028]
  -> + Variable 4: 'conc_hemoglobina_media' | Nuevo Score: 0.6951 | Tamaños N: [442, 452, 1025]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.6415 | Tamaños N: [417, 491, 1011]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7400) | Tamaños N: [496, 221, 1028, 174]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.6995 | Tamaños N: [435, 241, 1019, 224]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.6572 | Tamaños N: [452, 238, 1025, 204]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.5708 | Tamaños N: [491, 236, 1011, 181]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7274) | Tamaños N: [221, 205, 1028, 174, 291]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.6511 | Tamaños N: [241, 224, 1019, 195, 240]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.6027 | Tamaños N: [238, 204, 1025, 199, 253]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.5262 | Tamaños N: [1011, 236, 225, 181, 266]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 1 (Escalas Altas) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 3
  -> Silhouette Score Máximo: 0.7692
  -> Distribución (N): [395, 496, 1028]
  -> Variables (2): tiempo_seg_cond4, peso_flebotomia

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 2 (Escalas Medias)
============================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('tamano_hogar', 'ancho_distribucion_eritrocitos') (Score: 0.6681) | Tamaños N: [1393, 526]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.6572 | Tamaños N: [1393, 526]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.6302 | Tamaños N: [1393, 526]
  -> + Variable 5: 'eritrocitos_totales' | Nuevo Score: 0.5624 | Tamaños N: [1393, 526]
  -> + Variable 6: 'cap_iqr' | Nuevo Score: 0.5075 | Tamaños N: [1394, 525]
  -> + Variable 7: 'rigidez_mediana_kpa' | Nuevo Score: 0.4843 | Tamaños N: [1395, 524]
  -> + Variable 8: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.3914 | Tamaños N: [1455, 464]
  -> + Variable 9: 'ldl_martin_mmol_l' | Nuevo Score: 0.3520 | Tamaños N: [1404, 515]
  -> + Variable 10: 'ratio_albumina_creatinina' | Nuevo Score: 0.2957 | Tamaños N: [1391, 528]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tamano_hogar', 'ancho_distribucion_eritrocitos') (Score: 0.6747) | Tamaños N: [526, 980, 413]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.6431 | Tamaños N: [526, 980, 413]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.5726 | Tamaños N: [526, 980, 413]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.5362 | Tamaños N: [759, 1064, 96]
  -> + Variable 6: 'eritrocitos_totales' | Nuevo Score: 0.4608 | Tamaños N: [752, 1071, 96]
  -> + Variable 7: 'ratio_albumina_creatinina' | Nuevo Score: 0.4229 | Tamaños N: [1288, 550, 81]
  -> + Variable 8: 'cap_iqr' | Nuevo Score: 0.3504 | Tamaños N: [1198, 516, 205]
  -> + Variable 9: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.3069 | Tamaños N: [810, 1031, 78]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.2690 | Tamaños N: [1246, 528, 145]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tamano_hogar', 'ancho_distribucion_eritrocitos') (Score: 0.6850) | Tamaños N: [980, 429, 413, 97]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.6505 | Tamaños N: [980, 429, 413, 97]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.5742 | Tamaños N: [980, 429, 413, 97]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.4710 | Tamaños N: [1064, 425, 96, 334]
  -> + Variable 6: 'cap_iqr' | Nuevo Score: 0.3659 | Tamaños N: [620, 656, 230, 413]
  -> + Variable 7: 'eritrocitos_totales' | Nuevo Score: 0.2969 | Tamaños N: [993, 427, 402, 97]
  -> + Variable 8: 'ratio_albumina_creatinina' | Nuevo Score: 0.2441 | Tamaños N: [516, 838, 205, 360]
  -> + Variable 9: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.2465 | Tamaños N: [1031, 617, 78, 193]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.1409 | Tamaños N: [841, 405, 145, 528]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tamano_hogar', 'ancho_distribucion_eritrocitos') (Score: 0.8418) | Tamaños N: [429, 97, 413, 651, 329]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.7865 | Tamaños N: [429, 97, 413, 651, 329]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.6674 | Tamaños N: [429, 97, 413, 651, 329]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.4968 | Tamaños N: [425, 463, 96, 334, 601]
  -> + Variable 6: 'cap_iqr' | Nuevo Score: 0.3660 | Tamaños N: [230, 656, 326, 413, 294]
  -> + Variable 7: 'eritrocitos_totales' | Nuevo Score: 0.2742 | Tamaños N: [698, 427, 402, 97, 295]
  -> + Variable 8: 'ratio_albumina_creatinina' | Nuevo Score: 0.2239 | Tamaños N: [838, 431, 205, 360, 85]
  -> + Variable 9: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.1733 | Tamaños N: [617, 630, 78, 193, 401]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.1317 | Tamaños N: [405, 528, 145, 605, 236]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 2 (Escalas Medias) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 5
  -> Silhouette Score Máximo: 0.8418
  -> Distribución (N): [429, 97, 413, 651, 329]
  -> Variables (2): tamano_hogar, ancho_distribucion_eritrocitos

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 3 (Escalas Bajas)
============================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('trigliceridos_mmol_l', 'eosinofilos_abs') (Score: 0.5667) | Tamaños N: [1635, 284]
  -> + Variable 3: 'monocitos_abs' | Nuevo Score: 0.5199 | Tamaños N: [1656, 263]
  -> + Variable 4: 'plomo_sangre_umol_l' | Nuevo Score: 0.4845 | Tamaños N: [1627, 292]
  -> + Variable 5: 'hdl_mmol_l' | Nuevo Score: 0.3210 | Tamaños N: [831, 1088]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('trigliceridos_mmol_l', 'plomo_sangre_umol_l') (Score: 0.4642) | Tamaños N: [167, 1041, 711]
  -> + Variable 3: 'eosinofilos_abs' | Nuevo Score: 0.3460 | Tamaños N: [242, 1156, 521]
  -> + Variable 4: 'hdl_mmol_l' | Nuevo Score: 0.2925 | Tamaños N: [250, 1029, 640]
  -> + Variable 5: 'monocitos_abs' | Nuevo Score: 0.2514 | Tamaños N: [221, 1088, 610]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('trigliceridos_mmol_l', 'plomo_sangre_umol_l') (Score: 0.4574) | Tamaños N: [1041, 145, 711, 22]
  -> + Variable 3: 'eosinofilos_abs' | Nuevo Score: 0.3517 | Tamaños N: [1156, 221, 521, 21]
  -> + Variable 4: 'hdl_mmol_l' | Nuevo Score: 0.2889 | Tamaños N: [1029, 217, 640, 33]
  -> + Variable 5: 'monocitos_abs' | Nuevo Score: 0.2494 | Tamaños N: [1088, 200, 610, 21]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('eosinofilos_abs', 'plomo_sangre_umol_l') (Score: 0.4100) | Tamaños N: [159, 55, 791, 543, 371]
  -> + Variable 3: 'trigliceridos_mmol_l' | Nuevo Score: 0.2700 | Tamaños N: [606, 221, 521, 21, 550]
  -> + Variable 4: 'monocitos_abs' | Nuevo Score: 0.2469 | Tamaños N: [905, 65, 409, 227, 313]
  -> + Variable 5: 'hdl_mmol_l' | Nuevo Score: 0.1562 | Tamaños N: [704, 384, 610, 21, 200]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 3 (Escalas Bajas) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 2
  -> Silhouette Score Máximo: 0.5667
  -> Distribución (N): [1635, 284]
  -> Variables (2): trigliceridos_mmol_l, eosinofilos_abs

Con Clustering GMM

In [12]:
from sklearn.mixture import GaussianMixture
# 1. Definición de los grupos de variables por escala
grupos_escalas = {
    "Grupo 1 (Escalas Altas)": [
        'conc_hemoglobina_media', 'tiempo_seg_cond4', 'hemoglobina_g_dl',
        'peso_flebotomia', 'volumen_plaquetario_medio'
    ],
    "Grupo 2 (Escalas Medias)": [
        'eritrocitos_totales', 'cap_iqr', 'ldl_martin_mmol_l', 'tamano_hogar',
        'ancho_distribucion_eritrocitos', 'ratio_albumina_creatinina',
        'rigidez_mediana_kpa', 'proteina_c_reactiva_mg_l', 'selenio_sangre_umol_l',
        'linfocitos_abs'
    ],
    "Grupo 3 (Escalas Bajas)": [
        'hdl_mmol_l', 'trigliceridos_mmol_l', 'monocitos_abs',
        'eosinofilos_abs', 'plomo_sangre_umol_l'
    ]
}

print("=" * 80)
print("FORWARD SELECTION POR GRUPOS DE ESCALAS (CLUSTERING GMM)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 20    # Límite máximo general (se ajustará por grupo)

# Iteramos sobre cada grupo de variables
for nombre_grupo, variables_grupo in grupos_escalas.items():
    print("\n" + "=" * 60)
    print(f"🚀 INICIANDO ANÁLISIS PARA: {nombre_grupo}")
    print("=" * 60)

    # Filtrar solo las columnas de var_num_log que existen en el grupo
    columnas_totales_grupo = [col for col in variables_grupo if col in var_num_log.columns]

    # Ajustar el máximo de variables a iterar al tamaño real del grupo
    max_vars_grupo = min(max_variables, len(columnas_totales_grupo))

    if max_vars_grupo < 2:
        print(f"⚠️ El {nombre_grupo} tiene menos de 2 variables disponibles. Saltando...")
        continue

    resultados_finales = {}
    campeon_global_score = -1
    campeon_global_k = -1
    campeon_global_vars = []
    campeon_global_conteos = []

    for k in rango_k:
        print(f"\n[ Iniciando búsqueda para K={k} ]")

        columnas_disponibles = columnas_totales_grupo.copy()
        variables_seleccionadas = []

        # --- PASO 1: Buscar el mejor PAR inicial ---
        mejor_score_par = -1
        mejor_par = ()
        mejor_labels_par = None

        for combo in combinations(columnas_disponibles, 2):
            X_subset = var_num_log[list(combo)]

            # Instanciamos y ajustamos GMM
            gmm = GaussianMixture(n_components=k, random_state=42)
            labels = gmm.fit_predict(X_subset)

            score = silhouette_score(X_subset, labels)

            if score > mejor_score_par:
                mejor_score_par = score
                mejor_par = combo
                mejor_labels_par = labels

        # Consolidar el mejor par
        variables_seleccionadas.extend(mejor_par)
        for var in mejor_par:
            columnas_disponibles.remove(var)

        conteos_par = np.bincount(mejor_labels_par).tolist()

        print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

        historial_scores = [mejor_score_par]
        historial_conteos = [conteos_par]

        # --- PASO 2: Forward Selection ---
        for paso in range(3, max_vars_grupo + 1):
            mejor_score_paso = -1
            mejor_variable_paso = None
            mejor_labels_paso = None

            for var_candidata in columnas_disponibles:
                features_a_probar = variables_seleccionadas + [var_candidata]
                X_subset = var_num_log[features_a_probar]

                # Instanciamos y ajustamos GMM
                gmm = GaussianMixture(n_components=k, random_state=42)
                labels = gmm.fit_predict(X_subset)

                score = silhouette_score(X_subset, labels)

                if score > mejor_score_paso:
                    mejor_score_paso = score
                    mejor_variable_paso = var_candidata
                    mejor_labels_paso = labels

            # Consolidar variable ganadora
            variables_seleccionadas.append(mejor_variable_paso)
            columnas_disponibles.remove(mejor_variable_paso)

            conteos_paso = np.bincount(mejor_labels_paso).tolist()

            historial_scores.append(mejor_score_paso)
            historial_conteos.append(conteos_paso)

            print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

        # --- PASO 3: Encontrar el pico máximo ---
        indice_mejor_momento = historial_scores.index(max(historial_scores))
        score_pico = historial_scores[indice_mejor_momento]
        conteos_pico = historial_conteos[indice_mejor_momento]

        vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

        resultados_finales[k] = {
            'score': score_pico,
            'variables': vars_en_pico,
            'conteos': conteos_pico
        }

        if score_pico > campeon_global_score:
            campeon_global_score = score_pico
            campeon_global_k = k
            campeon_global_vars = vars_en_pico
            campeon_global_conteos = conteos_pico

    # Imprimir resumen final por grupo
    print("\n" + "-" * 60)
    print(f"🏆 RESULTADOS: {nombre_grupo} 🏆")
    print("-" * 60)
    print(f"🌟 EL CAMPEÓN DEL GRUPO:")
    print(f"  -> K Óptimo: {campeon_global_k}")
    print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
    print(f"  -> Distribución (N): {campeon_global_conteos}")
    print(f"  -> Variables ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

================================================================================
FORWARD SELECTION POR GRUPOS DE ESCALAS (CLUSTERING GMM)
================================================================================

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 1 (Escalas Altas)
============================================================

[ Iniciando búsqueda para K=2 ]

  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.6667) | Tamaños N: [1006, 913]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.6480 | Tamaños N: [1006, 913]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.6326 | Tamaños N: [1006, 913]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.6069 | Tamaños N: [1006, 913]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7432) | Tamaños N: [1006, 454, 459]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.7106 | Tamaños N: [1006, 460, 453]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.6825 | Tamaños N: [1006, 461, 452]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.6354 | Tamaños N: [1006, 460, 453]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7435) | Tamaños N: [1006, 453, 257, 203]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.6877 | Tamaños N: [1006, 452, 258, 203]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.6328 | Tamaños N: [1006, 407, 251, 255]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.5687 | Tamaños N: [1006, 409, 250, 254]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'peso_flebotomia') (Score: 0.7247) | Tamaños N: [1006, 334, 210, 200, 169]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.6605 | Tamaños N: [1006, 333, 210, 200, 170]
  -> + Variable 4: 'hemoglobina_g_dl' | Nuevo Score: 0.3783 | Tamaños N: [750, 415, 239, 256, 259]
  -> + Variable 5: 'volumen_plaquetario_medio' | Nuevo Score: 0.3580 | Tamaños N: [169, 426, 256, 231, 837]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 1 (Escalas Altas) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 4
  -> Silhouette Score Máximo: 0.7435
  -> Distribución (N): [1006, 453, 257, 203]
  -> Variables (2): tiempo_seg_cond4, peso_flebotomia

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 2 (Escalas Medias)
============================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('ratio_albumina_creatinina', 'linfocitos_abs') (Score: 0.6616) | Tamaños N: [1725, 194]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.5864 | Tamaños N: [1717, 202]
  -> + Variable 4: 'eritrocitos_totales' | Nuevo Score: 0.5175 | Tamaños N: [1712, 207]
  -> + Variable 5: 'cap_iqr' | Nuevo Score: 0.4633 | Tamaños N: [1713, 206]
  -> + Variable 6: 'rigidez_mediana_kpa' | Nuevo Score: 0.3927 | Tamaños N: [1646, 273]
  -> + Variable 7: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.3415 | Tamaños N: [1616, 303]
  -> + Variable 8: 'ldl_martin_mmol_l' | Nuevo Score: 0.2913 | Tamaños N: [316, 1603]
  -> + Variable 9: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.2387 | Tamaños N: [371, 1548]
  -> + Variable 10: 'tamano_hogar' | Nuevo Score: 0.1725 | Tamaños N: [396, 1523]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tamano_hogar', 'linfocitos_abs') (Score: 0.6275) | Tamaños N: [625, 1064, 230]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.5176 | Tamaños N: [329, 1064, 526]
  -> + Variable 4: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.4665 | Tamaños N: [326, 1032, 561]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.3845 | Tamaños N: [326, 1030, 563]
  -> + Variable 6: 'ratio_albumina_creatinina' | Nuevo Score: 0.3202 | Tamaños N: [948, 318, 653]
  -> + Variable 7: 'eritrocitos_totales' | Nuevo Score: 0.2933 | Tamaños N: [964, 313, 642]
  -> + Variable 8: 'cap_iqr' | Nuevo Score: 0.2721 | Tamaños N: [686, 925, 308]
  -> + Variable 9: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.2031 | Tamaños N: [735, 324, 860]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.1782 | Tamaños N: [644, 913, 362]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tamano_hogar', 'selenio_sangre_umol_l') (Score: 0.7555) | Tamaños N: [329, 651, 526, 413]
  -> + Variable 3: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.5933 | Tamaños N: [656, 649, 411, 203]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.4770 | Tamaños N: [324, 1024, 366, 205]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.4476 | Tamaños N: [326, 1059, 294, 240]
  -> + Variable 6: 'eritrocitos_totales' | Nuevo Score: 0.2971 | Tamaños N: [324, 1014, 366, 215]
  -> + Variable 7: 'ratio_albumina_creatinina' | Nuevo Score: 0.2230 | Tamaños N: [560, 233, 227, 899]
  -> + Variable 8: 'cap_iqr' | Nuevo Score: 0.1577 | Tamaños N: [711, 410, 158, 640]
  -> + Variable 9: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.1838 | Tamaños N: [562, 263, 883, 211]
  -> + Variable 10: 'ldl_martin_mmol_l' | Nuevo Score: 0.1477 | Tamaños N: [540, 877, 285, 217]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tamano_hogar', 'ancho_distribucion_eritrocitos') (Score: 0.8684) | Tamaños N: [329, 651, 230, 413, 296]
  -> + Variable 3: 'selenio_sangre_umol_l' | Nuevo Score: 0.7441 | Tamaños N: [324, 650, 411, 151, 383]
  -> + Variable 4: 'linfocitos_abs' | Nuevo Score: 0.6291 | Tamaños N: [324, 650, 385, 149, 411]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.4795 | Tamaños N: [329, 1063, 295, 99, 133]
  -> + Variable 6: 'cap_iqr' | Nuevo Score: 0.3691 | Tamaños N: [329, 651, 413, 230, 296]
  -> + Variable 7: 'eritrocitos_totales' | Nuevo Score: 0.2618 | Tamaños N: [324, 649, 411, 153, 382]
  -> + Variable 8: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.1534 | Tamaños N: [66, 644, 409, 639, 161]
  -> + Variable 9: 'ldl_martin_mmol_l' | Nuevo Score: 0.1095 | Tamaños N: [54, 410, 642, 490, 323]
  -> + Variable 10: 'ratio_albumina_creatinina' | Nuevo Score: 0.0338 | Tamaños N: [744, 564, 123, 244, 244]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 2 (Escalas Medias) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 5
  -> Silhouette Score Máximo: 0.8684
  -> Distribución (N): [329, 651, 230, 413, 296]
  -> Variables (2): tamano_hogar, ancho_distribucion_eritrocitos

============================================================
🚀 INICIANDO ANÁLISIS PARA: Grupo 3 (Escalas Bajas)
============================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('hdl_mmol_l', 'trigliceridos_mmol_l') (Score: 0.4999) | Tamaños N: [426, 1493]
  -> + Variable 3: 'monocitos_abs' | Nuevo Score: 0.3938 | Tamaños N: [507, 1412]
  -> + Variable 4: 'eosinofilos_abs' | Nuevo Score: 0.2833 | Tamaños N: [547, 1372]
  -> + Variable 5: 'plomo_sangre_umol_l' | Nuevo Score: 0.2273 | Tamaños N: [672, 1247]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('eosinofilos_abs', 'plomo_sangre_umol_l') (Score: 0.5034) | Tamaños N: [411, 1396, 112]
  -> + Variable 3: 'monocitos_abs' | Nuevo Score: 0.3442 | Tamaños N: [550, 1271, 98]
  -> + Variable 4: 'hdl_mmol_l' | Nuevo Score: 0.2454 | Tamaños N: [1413, 139, 367]
  -> + Variable 5: 'trigliceridos_mmol_l' | Nuevo Score: 0.1074 | Tamaños N: [352, 201, 1366]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('eosinofilos_abs', 'plomo_sangre_umol_l') (Score: 0.4010) | Tamaños N: [864, 812, 47, 196]
  -> + Variable 3: 'monocitos_abs' | Nuevo Score: 0.1987 | Tamaños N: [210, 810, 62, 837]
  -> + Variable 4: 'hdl_mmol_l' | Nuevo Score: 0.0921 | Tamaños N: [802, 69, 239, 809]
  -> + Variable 5: 'trigliceridos_mmol_l' | Nuevo Score: 0.1068 | Tamaños N: [203, 176, 449, 1091]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('monocitos_abs', 'plomo_sangre_umol_l') (Score: 0.3942) | Tamaños N: [694, 264, 32, 704, 225]
  -> + Variable 3: 'trigliceridos_mmol_l' | Nuevo Score: 0.2318 | Tamaños N: [337, 1161, 331, 31, 59]
  -> + Variable 4: 'hdl_mmol_l' | Nuevo Score: 0.1493 | Tamaños N: [286, 97, 79, 681, 776]
  -> + Variable 5: 'eosinofilos_abs' | Nuevo Score: 0.0139 | Tamaños N: [79, 59, 464, 806, 511]

------------------------------------------------------------
🏆 RESULTADOS: Grupo 3 (Escalas Bajas) 🏆
------------------------------------------------------------
🌟 EL CAMPEÓN DEL GRUPO:
  -> K Óptimo: 3
  -> Silhouette Score Máximo: 0.5034
  -> Distribución (N): [411, 1396, 112]
  -> Variables (2): eosinofilos_abs, plomo_sangre_umol_l

### ESTANDARIZACIÓN
Tras aplicar la transformación logaritmica estandarizamos el conjunto de datos.

In [10]:

scaler = StandardScaler()
datos_escalados_array = scaler.fit_transform(var_num_log)

In [11]:
var_num_log_scaled = pd.DataFrame(
    datos_escalados_array,
    columns=var_num_log.columns, # Recuperamos los nombres de las columnas
    index=var_num_log.index      # Recuperamos los índices originales
)
var_num_log_scaled.head(10)

,edad_an,tamano_hogar,ratio_pobreza,tiempo_seg_cond4,pulso,altura_cm,imc,largo_pierna_superior_cm,largo_brazo_superior_cm,rigidez_mediana_kpa,...,conc_hemoglobina_media,ancho_distribucion_eritrocitos,plaquetas_totales,volumen_plaquetario_medio,trigliceridos_mmol_l,ldl_martin_mmol_l,hdl_mmol_l,plomo_sangre_umol_l,selenio_sangre_umol_l,manganeso_sangre_nmol_l
0,-0.188751,1.575278,0.984181,0.810059,-0.438261,-1.541547,2.237715,-0.965813,-1.984451,0.788129,...,0.434668,0.335281,-0.148788,-0.064880,-0.217923,0.564297,0.991320,-1.128475,0.358438,0.143478
1,0.575265,0.208042,-0.578577,0.810059,0.158633,-0.490585,2.124402,-1.332158,-0.759037,3.035058,...,-3.080375,1.460799,1.324984,-1.395746,2.836066,-0.674377,-1.076357,-0.913991,-0.554631,-2.931749
2,-0.049839,0.208042,1.226568,0.810059,-0.352991,0.621010,0.084882,0.922273,0.641436,-0.790142,...,0.786172,-0.624857,-1.146655,0.933270,-0.629579,0.004270,0.050606,-0.913991,0.328263,1.263090
3,-0.605487,1.575278,0.021012,0.810059,0.840797,1.136385,-0.556256,1.485880,0.816495,-0.969417,...,-0.385509,-0.267257,-0.440472,0.489648,-0.113511,1.921592,0.050606,0.263839,0.298000,-0.321799
4,1.200370,0.208042,0.250642,-1.268443,2.716750,0.378480,-0.420615,0.302304,0.606424,0.820295,...,-0.502677,1.383632,-0.302306,-1.395746,1.260745,-1.470505,0.742922,2.202996,3.024857,0.752001
5,-1.508416,-0.475576,1.226568,0.810059,-0.182450,-1.460704,-1.282279,-1.163075,-1.669345,-0.081482,...,-0.971350,1.227876,-0.102733,1.376892,-1.218732,-1.323370,1.641699,16.169732,0.972513,1.507047
6,1.408738,-1.159194,-0.412733,0.810059,-1.802591,-0.965539,0.777208,-0.655829,-0.513955,1.005687,...,-0.268341,0.335281,-0.271603,0.156931,-0.670505,-0.762202,0.537385,0.318915,-0.488996,0.709928
7,-1.091680,1.575278,-1.292981,0.810059,-1.120426,0.216793,0.024675,0.247010,0.180119,-0.126409,...,-0.151173,-0.444798,0.588098,-0.619407,0.523314,0.291392,-0.394170,0.091336,0.328263,-0.478391
8,0.366897,0.891660,1.226568,0.054240,0.158633,0.348164,0.457969,-0.148582,-0.513955,0.755577,...,1.372012,-0.807507,-0.087381,-0.952124,2.461369,-0.142865,-1.142999,-0.159167,-0.521761,-1.554410
9,-0.605487,-1.159194,1.226568,-1.835307,-1.717320,0.732169,-1.262144,0.386845,0.116258,0.173519,...,0.903340,-0.534508,-0.732157,-0.064880,-1.170429,-1.027958,-0.265184,0.603880,1.224884,-2.172327

In [12]:
var_num_log_scaled.shape

(1919, 33)

K-Means

In [16]:
print("=" * 80)
print("FORWARD SELECTION CON TAMAÑO DE CLÚSTERES (N)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 20    # Límite máximo de variables a agrupar
columnas_totales = var_num_log_scaled.columns.tolist()

resultados_finales = {}
campeon_global_score = -1
campeon_global_k = -1
campeon_global_vars = []
campeon_global_conteos = []

for k in rango_k:
    print(f"\n[ Iniciando búsqueda para K={k} ]")

    columnas_disponibles = columnas_totales.copy()
    variables_seleccionadas = []

    # --- PASO 1: Buscar el mejor PAR inicial (La base sólida) ---
    mejor_score_par = -1
    mejor_par = ()
    mejor_labels_par = None

    # Probamos las parejas posibles
    for combo in combinations(columnas_disponibles, 2):
        X_subset = var_num_log_scaled[list(combo)]
        kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
        labels = kmeans.fit_predict(X_subset)
        score = silhouette_score(X_subset, labels)

        if score > mejor_score_par:
            mejor_score_par = score
            mejor_par = combo
            mejor_labels_par = labels # Guardamos las etiquetas ganadoras

    # Fijamos el mejor par y lo sacamos de las disponibles
    variables_seleccionadas.extend(mejor_par)
    for var in mejor_par:
        columnas_disponibles.remove(var)

    # Calculamos N por clúster
    conteos_par = np.bincount(mejor_labels_par).tolist()

    print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

    # Guardamos el historial de scores y conteos
    historial_scores = [mejor_score_par]
    historial_conteos = [conteos_par]

    # --- PASO 2: Forward Selection (Añadir 1 a 1 hasta max_variables) ---
    for paso in range(3, max_variables + 1):
        mejor_score_paso = -1
        mejor_variable_paso = None
        mejor_labels_paso = None

        # Probamos a añadir cada una de las variables que quedan libres
        for var_candidata in columnas_disponibles:
            features_a_probar = variables_seleccionadas + [var_candidata]
            X_subset = var_num_log_scaled[features_a_probar]

            kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
            labels = kmeans.fit_predict(X_subset)
            score = silhouette_score(X_subset, labels)

            if score > mejor_score_paso:
                mejor_score_paso = score
                mejor_variable_paso = var_candidata
                mejor_labels_paso = labels # Guardamos las etiquetas ganadoras

        # Consolidamos la variable ganadora de este paso
        variables_seleccionadas.append(mejor_variable_paso)
        columnas_disponibles.remove(mejor_variable_paso)

        # Calculamos N por clúster
        conteos_paso = np.bincount(mejor_labels_paso).tolist()

        historial_scores.append(mejor_score_paso)
        historial_conteos.append(conteos_paso)

        print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

    # --- PASO 3: Encontrar el pico máximo para este K ---
    indice_mejor_momento = historial_scores.index(max(historial_scores))
    score_pico = historial_scores[indice_mejor_momento]
    conteos_pico = historial_conteos[indice_mejor_momento]

    # El índice 0 equivale a 2 variables, índice 1 a 3 variables, etc.
    vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

    resultados_finales[k] = {
        'score': score_pico,
        'variables': vars_en_pico,
        'conteos': conteos_pico
    }

    # Actualizar campeón global absoluto
    if score_pico > campeon_global_score:
        campeon_global_score = score_pico
        campeon_global_k = k
        campeon_global_vars = vars_en_pico
        campeon_global_conteos = conteos_pico

print("\n" + "=" * 80)
print("🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆")
print("=" * 80)

print(f"\n🌟 EL CAMPEÓN ABSOLUTO:")
print(f"  -> K Óptimo: {campeon_global_k}")
print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
print(f"  -> Distribución de Pacientes (N): {campeon_global_conteos}")
print(f"  -> Variables óptimas ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

print("\n--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---")
for k in rango_k:
    res = resultados_finales[k]
    print(f"\nPara K={k}:")
    print(f"  -> Silhouette Score: {res['score']:.4f}")
    print(f"  -> Distribución de Pacientes (N): {res['conteos']}")
    print(f"  -> N Variables: {len(res['variables'])}")
    print(f"  -> Variables: {', '.join(res['variables'])}")

================================================================================
FORWARD SELECTION CON TAMAÑO DE CLÚSTERES (N)
================================================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('volumen_corpuscular_medio', 'ancho_distribucion_eritrocitos') (Score: 0.5409) | Tamaños N: [274, 1645]
  -> + Variable 3: 'hemoglobina_g_dl' | Nuevo Score: 0.4607 | Tamaños N: [279, 1640]
  -> + Variable 4: 'plomo_sangre_umol_l' | Nuevo Score: 0.4066 | Tamaños N: [282, 1637]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.3565 | Tamaños N: [279, 1640]
  -> + Variable 6: 'eosinofilos_abs' | Nuevo Score: 0.3254 | Tamaños N: [1656, 263]
  -> + Variable 7: 'ratio_albumina_creatinina' | Nuevo Score: 0.2887 | Tamaños N: [1538, 381]
  -> + Variable 8: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.2672 | Tamaños N: [332, 1587]
  -> + Variable 9: 'trigliceridos_mmol_l' | Nuevo Score: 0.2579 | Tamaños N: [1618, 301]
  -> + Variable 10: 'largo_pierna_superior_cm' | Nuevo Score: 0.2357 | Tamaños N: [1617, 302]
  -> + Variable 11: 'volumen_plaquetario_medio' | Nuevo Score: 0.2214 | Tamaños N: [1620, 299]
  -> + Variable 12: 'peso_flebotomia' | Nuevo Score: 0.2011 | Tamaños N: [1611, 308]
  -> + Variable 13: 'monocitos_abs' | Nuevo Score: 0.1899 | Tamaños N: [1611, 308]
  -> + Variable 14: 'conc_hemoglobina_media' | Nuevo Score: 0.1489 | Tamaños N: [1485, 434]
  -> + Variable 15: 'plaquetas_totales' | Nuevo Score: 0.1699 | Tamaños N: [1571, 348]
  -> + Variable 16: 'tamano_hogar' | Nuevo Score: 0.1417 | Tamaños N: [1476, 443]
  -> + Variable 17: 'edad_an' | Nuevo Score: 0.1336 | Tamaños N: [1475, 444]
  -> + Variable 18: 'tiempo_seg_cond4' | Nuevo Score: 0.1252 | Tamaños N: [1468, 451]
  -> + Variable 19: 'creatinina_orina_umol_l' | Nuevo Score: 0.1161 | Tamaños N: [1457, 462]
  -> + Variable 20: 'imc' | Nuevo Score: 0.1064 | Tamaños N: [1280, 639]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'ancho_distribucion_eritrocitos') (Score: 0.5574) | Tamaños N: [1123, 609, 187]
  -> + Variable 3: 'volumen_corpuscular_medio' | Nuevo Score: 0.4226 | Tamaños N: [197, 612, 1110]
  -> + Variable 4: 'plomo_sangre_umol_l' | Nuevo Score: 0.3477 | Tamaños N: [1121, 611, 187]
  -> + Variable 5: 'ratio_albumina_creatinina' | Nuevo Score: 0.2910 | Tamaños N: [1114, 190, 615]
  -> + Variable 6: 'conc_hemoglobina_media' | Nuevo Score: 0.2513 | Tamaños N: [1104, 207, 608]
  -> + Variable 7: 'rigidez_mediana_kpa' | Nuevo Score: 0.2216 | Tamaños N: [618, 1094, 207]
  -> + Variable 8: 'eosinofilos_abs' | Nuevo Score: 0.1949 | Tamaños N: [1089, 213, 617]
  -> + Variable 9: 'monocitos_abs' | Nuevo Score: 0.1745 | Tamaños N: [578, 229, 1112]
  -> + Variable 10: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.1694 | Tamaños N: [567, 1130, 222]
  -> + Variable 11: 'leucocitos_totales' | Nuevo Score: 0.1681 | Tamaños N: [631, 176, 1112]
  -> + Variable 12: 'imc' | Nuevo Score: 0.1611 | Tamaños N: [663, 1078, 178]
  -> + Variable 13: 'cap_mediana_db_m' | Nuevo Score: 0.1588 | Tamaños N: [184, 1066, 669]
  -> + Variable 14: 'plaquetas_totales' | Nuevo Score: 0.1553 | Tamaños N: [643, 1086, 190]
  -> + Variable 15: 'hemoglobina_g_dl' | Nuevo Score: 0.1487 | Tamaños N: [646, 1079, 194]
  -> + Variable 16: 'volumen_plaquetario_medio' | Nuevo Score: 0.1399 | Tamaños N: [641, 1085, 193]
  -> + Variable 17: 'largo_pierna_superior_cm' | Nuevo Score: 0.1325 | Tamaños N: [194, 1079, 646]
  -> + Variable 18: 'linfocitos_abs' | Nuevo Score: 0.1273 | Tamaños N: [652, 1053, 214]
  -> + Variable 19: 'peso_flebotomia' | Nuevo Score: 0.1225 | Tamaños N: [635, 1069, 215]
  -> + Variable 20: 'ratio_pobreza' | Nuevo Score: 0.1153 | Tamaños N: [656, 1039, 224]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'eosinofilos_abs') (Score: 0.5375) | Tamaños N: [563, 577, 617, 162]
  -> + Variable 3: 'ratio_albumina_creatinina' | Nuevo Score: 0.4195 | Tamaños N: [313, 519, 152, 935]
  -> + Variable 4: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.3371 | Tamaños N: [1058, 536, 157, 168]
  -> + Variable 5: 'volumen_corpuscular_medio' | Nuevo Score: 0.2797 | Tamaños N: [1042, 525, 171, 181]
  -> + Variable 6: 'plomo_sangre_umol_l' | Nuevo Score: 0.2361 | Tamaños N: [1034, 218, 164, 503]
  -> + Variable 7: 'conc_hemoglobina_media' | Nuevo Score: 0.2078 | Tamaños N: [167, 1031, 192, 529]
  -> + Variable 8: 'rigidez_mediana_kpa' | Nuevo Score: 0.1815 | Tamaños N: [285, 907, 540, 187]
  -> + Variable 9: 'ratio_pobreza' | Nuevo Score: 0.1675 | Tamaños N: [612, 196, 1017, 94]
  -> + Variable 10: 'imc' | Nuevo Score: 0.1482 | Tamaños N: [311, 176, 911, 521]
  -> + Variable 11: 'cap_mediana_db_m' | Nuevo Score: 0.1336 | Tamaños N: [447, 492, 815, 165]
  -> + Variable 12: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.1253 | Tamaños N: [175, 460, 824, 460]
  -> + Variable 13: 'leucocitos_totales' | Nuevo Score: 0.1182 | Tamaños N: [166, 500, 812, 441]
  -> + Variable 14: 'largo_pierna_superior_cm' | Nuevo Score: 0.1118 | Tamaños N: [175, 485, 450, 809]
  -> + Variable 15: 'pulso' | Nuevo Score: 0.1048 | Tamaños N: [166, 484, 452, 817]
  -> + Variable 16: 'linfocitos_abs' | Nuevo Score: 0.0995 | Tamaños N: [508, 176, 795, 440]
  -> + Variable 17: 'ldl_martin_mmol_l' | Nuevo Score: 0.0935 | Tamaños N: [504, 794, 433, 188]
  -> + Variable 18: 'monocitos_abs' | Nuevo Score: 0.0878 | Tamaños N: [545, 422, 167, 785]
  -> + Variable 19: 'selenio_sangre_umol_l' | Nuevo Score: 0.0894 | Tamaños N: [507, 173, 454, 785]
  -> + Variable 20: 'volumen_plaquetario_medio' | Nuevo Score: 0.0922 | Tamaños N: [407, 451, 197, 864]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'eosinofilos_abs') (Score: 0.5536) | Tamaños N: [246, 574, 584, 88, 427]
  -> + Variable 3: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.4013 | Tamaños N: [253, 893, 560, 158, 55]
  -> + Variable 4: 'ratio_albumina_creatinina' | Nuevo Score: 0.3563 | Tamaños N: [978, 146, 144, 150, 501]
  -> + Variable 5: 'volumen_corpuscular_medio' | Nuevo Score: 0.2937 | Tamaños N: [961, 484, 147, 160, 167]
  -> + Variable 6: 'conc_hemoglobina_media' | Nuevo Score: 0.2491 | Tamaños N: [494, 177, 147, 962, 139]
  -> + Variable 7: 'eritrocitos_totales' | Nuevo Score: 0.2016 | Tamaños N: [919, 491, 131, 201, 177]
  -> + Variable 8: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.1670 | Tamaños N: [207, 200, 447, 171, 894]
  -> + Variable 9: 'imc' | Nuevo Score: 0.1468 | Tamaños N: [189, 439, 400, 741, 150]
  -> + Variable 10: 'rigidez_mediana_kpa' | Nuevo Score: 0.1365 | Tamaños N: [156, 454, 384, 170, 755]
  -> + Variable 11: 'leucocitos_totales' | Nuevo Score: 0.1236 | Tamaños N: [371, 733, 430, 164, 221]
  -> + Variable 12: 'plomo_sangre_umol_l' | Nuevo Score: 0.1108 | Tamaños N: [436, 413, 774, 153, 143]
  -> + Variable 13: 'monocitos_abs' | Nuevo Score: 0.1065 | Tamaños N: [359, 729, 416, 257, 158]
  -> + Variable 14: 'ratio_pobreza' | Nuevo Score: 0.1009 | Tamaños N: [313, 323, 422, 709, 152]
  -> + Variable 15: 'cap_mediana_db_m' | Nuevo Score: 0.0971 | Tamaños N: [280, 155, 717, 388, 379]
  -> + Variable 16: 'tamano_hogar' | Nuevo Score: 0.0888 | Tamaños N: [308, 691, 154, 401, 365]
  -> + Variable 17: 'linfocitos_abs' | Nuevo Score: 0.0776 | Tamaños N: [377, 368, 628, 146, 400]
  -> + Variable 18: 'selenio_sangre_umol_l' | Nuevo Score: 0.0704 | Tamaños N: [361, 342, 642, 422, 152]
  -> + Variable 19: 'edad_an' | Nuevo Score: 0.0702 | Tamaños N: [357, 145, 601, 349, 467]
  -> + Variable 20: 'hdl_mmol_l' | Nuevo Score: 0.0661 | Tamaños N: [335, 148, 570, 449, 417]

================================================================================
🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆
================================================================================

🌟 EL CAMPEÓN ABSOLUTO:
  -> K Óptimo: 3
  -> Silhouette Score Máximo: 0.5574
  -> Distribución de Pacientes (N): [1123, 609, 187]
  -> Variables óptimas (2): tiempo_seg_cond4, ancho_distribucion_eritrocitos

--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---

Para K=2:
  -> Silhouette Score: 0.5409
  -> Distribución de Pacientes (N): [274, 1645]
  -> N Variables: 2
  -> Variables: volumen_corpuscular_medio, ancho_distribucion_eritrocitos

Para K=3:
  -> Silhouette Score: 0.5574
  -> Distribución de Pacientes (N): [1123, 609, 187]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, ancho_distribucion_eritrocitos

Para K=4:
  -> Silhouette Score: 0.5375
  -> Distribución de Pacientes (N): [563, 577, 617, 162]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, eosinofilos_abs

Para K=5:
  -> Silhouette Score: 0.5536
  -> Distribución de Pacientes (N): [246, 574, 584, 88, 427]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, eosinofilos_abs

Clustering Jerarquico (tras transofrmar y estandarizar)

In [17]:
import numpy as np
from itertools import combinations
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

print("=" * 80)
print("FORWARD SELECTION: CLUSTERING JERÁRQUICO CON TAMAÑO (N)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 20    # Límite máximo de variables a agrupar
columnas_totales = var_num_log_scaled.columns.tolist()

resultados_finales = {}
campeon_global_score = -1
campeon_global_k = -1
campeon_global_vars = []
campeon_global_conteos = []

for k in rango_k:
    print(f"\n[ Iniciando búsqueda para K={k} ]")

    columnas_disponibles = columnas_totales.copy()
    variables_seleccionadas = []

    # --- PASO 1: Buscar el mejor PAR inicial (La base sólida) ---
    mejor_score_par = -1
    mejor_par = ()
    mejor_labels_par = None

    # Probamos las parejas posibles
    for combo in combinations(columnas_disponibles, 2):
        X_subset = var_num_log_scaled[list(combo)]

        # INSTANCIAMOS EL CLUSTERING JERÁRQUICO
        jerarquico = AgglomerativeClustering(n_clusters=k, linkage='ward')
        labels = jerarquico.fit_predict(X_subset)
        score = silhouette_score(X_subset, labels)

        if score > mejor_score_par:
            mejor_score_par = score
            mejor_par = combo
            mejor_labels_par = labels # Guardamos las etiquetas ganadoras

    # Fijamos el mejor par y lo sacamos de las disponibles
    variables_seleccionadas.extend(mejor_par)
    for var in mejor_par:
        columnas_disponibles.remove(var)

    # Calculamos N por clúster
    conteos_par = np.bincount(mejor_labels_par).tolist()

    print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

    # Guardamos el historial de scores y conteos
    historial_scores = [mejor_score_par]
    historial_conteos = [conteos_par]

    # --- PASO 2: Forward Selection (Añadir 1 a 1 hasta max_variables) ---
    for paso in range(3, max_variables + 1):
        mejor_score_paso = -1
        mejor_variable_paso = None
        mejor_labels_paso = None

        # Probamos a añadir cada una de las variables que quedan libres
        for var_candidata in columnas_disponibles:
            features_a_probar = variables_seleccionadas + [var_candidata]
            X_subset = var_num_log_scaled[features_a_probar]

            # INSTANCIAMOS EL CLUSTERING JERÁRQUICO
            jerarquico = AgglomerativeClustering(n_clusters=k, linkage='ward')
            labels = jerarquico.fit_predict(X_subset)
            score = silhouette_score(X_subset, labels)

            if score > mejor_score_paso:
                mejor_score_paso = score
                mejor_variable_paso = var_candidata
                mejor_labels_paso = labels # Guardamos las etiquetas ganadoras

        # Consolidamos la variable ganadora de este paso
        variables_seleccionadas.append(mejor_variable_paso)
        columnas_disponibles.remove(mejor_variable_paso)

        # Calculamos N por clúster
        conteos_paso = np.bincount(mejor_labels_paso).tolist()

        historial_scores.append(mejor_score_paso)
        historial_conteos.append(conteos_paso)

        print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

    # --- PASO 3: Encontrar el pico máximo para este K ---
    indice_mejor_momento = historial_scores.index(max(historial_scores))
    score_pico = historial_scores[indice_mejor_momento]
    conteos_pico = historial_conteos[indice_mejor_momento]

    # El índice 0 equivale a 2 variables, índice 1 a 3 variables, etc.
    vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

    resultados_finales[k] = {
        'score': score_pico,
        'variables': vars_en_pico,
        'conteos': conteos_pico
    }

    # Actualizar campeón global absoluto
    if score_pico > campeon_global_score:
        campeon_global_score = score_pico
        campeon_global_k = k
        campeon_global_vars = vars_en_pico
        campeon_global_conteos = conteos_pico

print("\n" + "=" * 80)
print("🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆")
print("=" * 80)

print(f"\n🌟 EL CAMPEÓN ABSOLUTO:")
print(f"  -> K Óptimo: {campeon_global_k}")
print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
print(f"  -> Distribución de Pacientes (N): {campeon_global_conteos}")
print(f"  -> Variables óptimas ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

print("\n--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---")
for k in rango_k:
    res = resultados_finales[k]
    print(f"\nPara K={k}:")
    print(f"  -> Silhouette Score: {res['score']:.4f}")
    print(f"  -> Distribución de Pacientes (N): {res['conteos']}")
    print(f"  -> N Variables: {len(res['variables'])}")
    print(f"  -> Variables: {', '.join(res['variables'])}")

================================================================================
FORWARD SELECTION: CLUSTERING JERÁRQUICO CON TAMAÑO (N)
================================================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('volumen_corpuscular_medio', 'ancho_distribucion_eritrocitos') (Score: 0.6256) | Tamaños N: [1789, 130]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.5999 | Tamaños N: [1829, 90]
  -> + Variable 4: 'hemoglobina_g_dl' | Nuevo Score: 0.5492 | Tamaños N: [1819, 100]
  -> + Variable 5: 'ratio_pobreza' | Nuevo Score: 0.5098 | Tamaños N: [1840, 79]
  -> + Variable 6: 'eritrocitos_totales' | Nuevo Score: 0.4714 | Tamaños N: [1829, 90]
  -> + Variable 7: 'trigliceridos_mmol_l' | Nuevo Score: 0.4283 | Tamaños N: [1822, 97]
  -> + Variable 8: 'ratio_albumina_creatinina' | Nuevo Score: 0.4086 | Tamaños N: [1823, 96]
  -> + Variable 9: 'creatinina_orina_umol_l' | Nuevo Score: 0.3969 | Tamaños N: [1838, 81]
  -> + Variable 10: 'cap_mediana_db_m' | Nuevo Score: 0.3363 | Tamaños N: [1807, 112]
  -> + Variable 11: 'largo_brazo_superior_cm' | Nuevo Score: 0.3547 | Tamaños N: [1836, 83]
  -> + Variable 12: 'eosinofilos_abs' | Nuevo Score: 0.3101 | Tamaños N: [1817, 102]
  -> + Variable 13: 'cap_iqr' | Nuevo Score: 0.2825 | Tamaños N: [1803, 116]
  -> + Variable 14: 'volumen_plaquetario_medio' | Nuevo Score: 0.2541 | Tamaños N: [1797, 122]
  -> + Variable 15: 'monocitos_abs' | Nuevo Score: 0.2358 | Tamaños N: [1798, 121]
  -> + Variable 16: 'peso_flebotomia' | Nuevo Score: 0.2394 | Tamaños N: [1810, 109]
  -> + Variable 17: 'leucocitos_totales' | Nuevo Score: 0.2358 | Tamaños N: [1812, 107]
  -> + Variable 18: 'tiempo_seg_cond4' | Nuevo Score: 0.1816 | Tamaños N: [1778, 141]
  -> + Variable 19: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.2078 | Tamaños N: [1797, 122]
  -> + Variable 20: 'rigidez_mediana_kpa' | Nuevo Score: 0.2022 | Tamaños N: [1803, 116]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'plomo_sangre_umol_l') (Score: 0.5304) | Tamaños N: [1397, 509, 13]
  -> + Variable 3: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.3897 | Tamaños N: [683, 1127, 109]
  -> + Variable 4: 'rigidez_mediana_kpa' | Nuevo Score: 0.3276 | Tamaños N: [518, 128, 1273]
  -> + Variable 5: 'volumen_corpuscular_medio' | Nuevo Score: 0.2633 | Tamaños N: [700, 1096, 123]
  -> + Variable 6: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.2285 | Tamaños N: [664, 1140, 115]
  -> + Variable 7: 'conc_hemoglobina_media' | Nuevo Score: 0.1984 | Tamaños N: [626, 182, 1111]
  -> + Variable 8: 'ratio_albumina_creatinina' | Nuevo Score: 0.1753 | Tamaños N: [682, 220, 1017]
  -> + Variable 9: 'eosinofilos_abs' | Nuevo Score: 0.1574 | Tamaños N: [675, 160, 1084]
  -> + Variable 10: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.1399 | Tamaños N: [703, 1118, 98]
  -> + Variable 11: 'cap_mediana_db_m' | Nuevo Score: 0.1278 | Tamaños N: [675, 166, 1078]
  -> + Variable 12: 'largo_pierna_superior_cm' | Nuevo Score: 0.1628 | Tamaños N: [1420, 345, 154]
  -> + Variable 13: 'trigliceridos_mmol_l' | Nuevo Score: 0.1440 | Tamaños N: [1358, 425, 136]
  -> + Variable 14: 'imc' | Nuevo Score: 0.1342 | Tamaños N: [1235, 540, 144]
  -> + Variable 15: 'peso_flebotomia' | Nuevo Score: 0.1288 | Tamaños N: [1333, 462, 124]
  -> + Variable 16: 'altura_cm' | Nuevo Score: 0.1475 | Tamaños N: [1400, 356, 163]
  -> + Variable 17: 'tamano_hogar' | Nuevo Score: 0.1586 | Tamaños N: [1480, 326, 113]
  -> + Variable 18: 'linfocitos_abs' | Nuevo Score: 0.1212 | Tamaños N: [1308, 442, 169]
  -> + Variable 19: 'ldl_martin_mmol_l' | Nuevo Score: 0.1096 | Tamaños N: [1295, 491, 133]
  -> + Variable 20: 'ratio_pobreza' | Nuevo Score: 0.0954 | Tamaños N: [1178, 593, 148]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'eosinofilos_abs') (Score: 0.5056) | Tamaños N: [1140, 458, 291, 30]
  -> + Variable 3: 'rigidez_mediana_kpa' | Nuevo Score: 0.3980 | Tamaños N: [1186, 470, 203, 60]
  -> + Variable 4: 'volumen_corpuscular_medio' | Nuevo Score: 0.3056 | Tamaños N: [144, 504, 1187, 84]
  -> + Variable 5: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.2614 | Tamaños N: [1204, 509, 140, 66]
  -> + Variable 6: 'ratio_albumina_creatinina' | Nuevo Score: 0.2201 | Tamaños N: [1204, 145, 147, 423]
  -> + Variable 7: 'conc_hemoglobina_media' | Nuevo Score: 0.1895 | Tamaños N: [1110, 494, 161, 154]
  -> + Variable 8: 'plomo_sangre_umol_l' | Nuevo Score: 0.1722 | Tamaños N: [175, 564, 118, 1062]
  -> + Variable 9: 'ratio_pobreza' | Nuevo Score: 0.1567 | Tamaños N: [604, 1152, 86, 77]
  -> + Variable 10: 'edad_an' | Nuevo Score: 0.1367 | Tamaños N: [674, 980, 141, 124]
  -> + Variable 11: 'linfocitos_abs' | Nuevo Score: 0.1238 | Tamaños N: [1111, 614, 93, 101]
  -> + Variable 12: 'peso_flebotomia' | Nuevo Score: 0.1100 | Tamaños N: [937, 586, 174, 222]
  -> + Variable 13: 'cap_mediana_db_m' | Nuevo Score: 0.0941 | Tamaños N: [1155, 182, 99, 483]
  -> + Variable 14: 'hemoglobina_g_dl' | Nuevo Score: 0.0905 | Tamaños N: [1165, 505, 101, 148]
  -> + Variable 15: 'monocitos_abs' | Nuevo Score: 0.0768 | Tamaños N: [907, 421, 158, 433]
  -> + Variable 16: 'eritrocitos_totales' | Nuevo Score: 0.0620 | Tamaños N: [826, 273, 156, 664]
  -> + Variable 17: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.0801 | Tamaños N: [1099, 506, 67, 247]
  -> + Variable 18: 'altura_cm' | Nuevo Score: 0.0633 | Tamaños N: [966, 625, 138, 190]
  -> + Variable 19: 'largo_pierna_superior_cm' | Nuevo Score: 0.0516 | Tamaños N: [666, 523, 143, 587]
  -> + Variable 20: 'largo_brazo_superior_cm' | Nuevo Score: 0.0887 | Tamaños N: [884, 656, 125, 254]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tiempo_seg_cond4', 'ancho_distribucion_eritrocitos') (Score: 0.5039) | Tamaños N: [1095, 234, 200, 384, 6]
  -> + Variable 3: 'eosinofilos_abs' | Nuevo Score: 0.3704 | Tamaños N: [233, 880, 124, 516, 166]
  -> + Variable 4: 'ratio_albumina_creatinina' | Nuevo Score: 0.3353 | Tamaños N: [1103, 101, 505, 119, 91]
  -> + Variable 5: 'plomo_sangre_umol_l' | Nuevo Score: 0.2639 | Tamaños N: [72, 994, 563, 207, 83]
  -> + Variable 6: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.2139 | Tamaños N: [624, 114, 1026, 118, 37]
  -> + Variable 7: 'volumen_corpuscular_medio' | Nuevo Score: 0.1773 | Tamaños N: [209, 105, 481, 1044, 80]
  -> + Variable 8: 'eritrocitos_totales' | Nuevo Score: 0.1604 | Tamaños N: [179, 1002, 134, 540, 64]
  -> + Variable 9: 'pulso' | Nuevo Score: 0.1404 | Tamaños N: [127, 1114, 131, 503, 44]
  -> + Variable 10: 'leucocitos_totales' | Nuevo Score: 0.1109 | Tamaños N: [353, 246, 929, 285, 106]
  -> + Variable 11: 'monocitos_abs' | Nuevo Score: 0.0968 | Tamaños N: [433, 837, 425, 123, 101]
  -> + Variable 12: 'edad_an' | Nuevo Score: 0.0946 | Tamaños N: [930, 324, 173, 401, 91]
  -> + Variable 13: 'ratio_pobreza' | Nuevo Score: 0.0833 | Tamaños N: [445, 374, 853, 81, 166]
  -> + Variable 14: 'selenio_sangre_umol_l' | Nuevo Score: 0.0724 | Tamaños N: [560, 827, 290, 137, 105]
  -> + Variable 15: 'imc' | Nuevo Score: 0.0582 | Tamaños N: [440, 299, 885, 76, 219]
  -> + Variable 16: 'largo_pierna_superior_cm' | Nuevo Score: 0.0586 | Tamaños N: [375, 677, 599, 63, 205]
  -> + Variable 17: 'trigliceridos_mmol_l' | Nuevo Score: 0.0568 | Tamaños N: [793, 480, 403, 57, 186]
  -> + Variable 18: 'cap_mediana_db_m' | Nuevo Score: 0.0559 | Tamaños N: [519, 827, 241, 60, 272]
  -> + Variable 19: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.0429 | Tamaños N: [504, 630, 296, 383, 106]
  -> + Variable 20: 'cap_iqr' | Nuevo Score: 0.0402 | Tamaños N: [821, 356, 353, 90, 299]

================================================================================
🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆
================================================================================

🌟 EL CAMPEÓN ABSOLUTO:
  -> K Óptimo: 2
  -> Silhouette Score Máximo: 0.6256
  -> Distribución de Pacientes (N): [1789, 130]
  -> Variables óptimas (2): volumen_corpuscular_medio, ancho_distribucion_eritrocitos

--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---

Para K=2:
  -> Silhouette Score: 0.6256
  -> Distribución de Pacientes (N): [1789, 130]
  -> N Variables: 2
  -> Variables: volumen_corpuscular_medio, ancho_distribucion_eritrocitos

Para K=3:
  -> Silhouette Score: 0.5304
  -> Distribución de Pacientes (N): [1397, 509, 13]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, plomo_sangre_umol_l

Para K=4:
  -> Silhouette Score: 0.5056
  -> Distribución de Pacientes (N): [1140, 458, 291, 30]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, eosinofilos_abs

Para K=5:
  -> Silhouette Score: 0.5039
  -> Distribución de Pacientes (N): [1095, 234, 200, 384, 6]
  -> N Variables: 2
  -> Variables: tiempo_seg_cond4, ancho_distribucion_eritrocitos

Clustering GMM (tras transofrmar y estandarizar)

In [18]:
import numpy as np
from itertools import combinations
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score

print("=" * 80)
print("FORWARD SELECTION: GAUSSIAN MIXTURE MODEL (GMM) CON TAMAÑO (N)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 20    # Límite máximo de variables a agrupar
columnas_totales = var_num_log_scaled.columns.tolist()

resultados_finales = {}
campeon_global_score = -1
campeon_global_k = -1
campeon_global_vars = []
campeon_global_conteos = []

for k in rango_k:
    print(f"\n[ Iniciando búsqueda para K={k} ]")

    columnas_disponibles = columnas_totales.copy()
    variables_seleccionadas = []

    # --- PASO 1: Buscar el mejor PAR inicial (La base sólida) ---
    mejor_score_par = -1
    mejor_par = ()
    mejor_labels_par = None

    # Probamos las parejas posibles
    for combo in combinations(columnas_disponibles, 2):
        X_subset = var_num_log_scaled[list(combo)]

        # INSTANCIAMOS EL GAUSSIAN MIXTURE MODEL
        # n_components es el equivalente a los clústeres en GMM
        gmm = GaussianMixture(n_components=k, random_state=42)
        labels = gmm.fit_predict(X_subset)
        score = silhouette_score(X_subset, labels)

        if score > mejor_score_par:
            mejor_score_par = score
            mejor_par = combo
            mejor_labels_par = labels # Guardamos las etiquetas ganadoras

    # Fijamos el mejor par y lo sacamos de las disponibles
    variables_seleccionadas.extend(mejor_par)
    for var in mejor_par:
        columnas_disponibles.remove(var)

    # Calculamos N por clúster
    conteos_par = np.bincount(mejor_labels_par).tolist()

    print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

    # Guardamos el historial de scores y conteos
    historial_scores = [mejor_score_par]
    historial_conteos = [conteos_par]

    # --- PASO 2: Forward Selection (Añadir 1 a 1 hasta max_variables) ---
    for paso in range(3, max_variables + 1):
        mejor_score_paso = -1
        mejor_variable_paso = None
        mejor_labels_paso = None

        # Probamos a añadir cada una de las variables que quedan libres
        for var_candidata in columnas_disponibles:
            features_a_probar = variables_seleccionadas + [var_candidata]
            X_subset = var_num_log_scaled[features_a_probar]

            # INSTANCIAMOS EL GAUSSIAN MIXTURE MODEL
            gmm = GaussianMixture(n_components=k, random_state=42)
            labels = gmm.fit_predict(X_subset)
            score = silhouette_score(X_subset, labels)

            if score > mejor_score_paso:
                mejor_score_paso = score
                mejor_variable_paso = var_candidata
                mejor_labels_paso = labels # Guardamos las etiquetas ganadoras

        # Consolidamos la variable ganadora de este paso
        variables_seleccionadas.append(mejor_variable_paso)
        columnas_disponibles.remove(mejor_variable_paso)

        # Calculamos N por clúster
        conteos_paso = np.bincount(mejor_labels_paso).tolist()

        historial_scores.append(mejor_score_paso)
        historial_conteos.append(conteos_paso)

        print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

    # --- PASO 3: Encontrar el pico máximo para este K ---
    indice_mejor_momento = historial_scores.index(max(historial_scores))
    score_pico = historial_scores[indice_mejor_momento]
    conteos_pico = historial_conteos[indice_mejor_momento]

    # El índice 0 equivale a 2 variables, índice 1 a 3 variables, etc.
    vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

    resultados_finales[k] = {
        'score': score_pico,
        'variables': vars_en_pico,
        'conteos': conteos_pico
    }

    # Actualizar campeón global absoluto
    if score_pico > campeon_global_score:
        campeon_global_score = score_pico
        campeon_global_k = k
        campeon_global_vars = vars_en_pico
        campeon_global_conteos = conteos_pico

print("\n" + "=" * 80)
print("🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆")
print("=" * 80)

print(f"\n🌟 EL CAMPEÓN ABSOLUTO:")
print(f"  -> K Óptimo: {campeon_global_k}")
print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
print(f"  -> Distribución de Pacientes (N): {campeon_global_conteos}")
print(f"  -> Variables óptimas ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

print("\n--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---")
for k in rango_k:
    res = resultados_finales[k]
    print(f"\nPara K={k}:")
    print(f"  -> Silhouette Score: {res['score']:.4f}")
    print(f"  -> Distribución de Pacientes (N): {res['conteos']}")
    print(f"  -> N Variables: {len(res['variables'])}")
    print(f"  -> Variables: {', '.join(res['variables'])}")

================================================================================
FORWARD SELECTION: GAUSSIAN MIXTURE MODEL (GMM) CON TAMAÑO (N)
================================================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('plomo_sangre_umol_l', 'selenio_sangre_umol_l') (Score: 0.5880) | Tamaños N: [1794, 125]
  -> + Variable 3: 'tamano_hogar' | Nuevo Score: 0.4863 | Tamaños N: [1797, 122]
  -> + Variable 4: 'cap_iqr' | Nuevo Score: 0.4202 | Tamaños N: [1791, 128]
  -> + Variable 5: 'eritrocitos_totales' | Nuevo Score: 0.3725 | Tamaños N: [136, 1783]
  -> + Variable 6: 'volumen_plaquetario_medio' | Nuevo Score: 0.3407 | Tamaños N: [142, 1777]
  -> + Variable 7: 'ldl_martin_mmol_l' | Nuevo Score: 0.3118 | Tamaños N: [140, 1779]
  -> + Variable 8: 'ratio_pobreza' | Nuevo Score: 0.2965 | Tamaños N: [1801, 118]
  -> + Variable 9: 'cap_mediana_db_m' | Nuevo Score: 0.2554 | Tamaños N: [157, 1762]
  -> + Variable 10: 'plaquetas_totales' | Nuevo Score: 0.2397 | Tamaños N: [1767, 152]
  -> + Variable 11: 'proteina_c_reactiva_mg_l' | Nuevo Score: 0.2224 | Tamaños N: [1732, 187]
  -> + Variable 12: 'peso_flebotomia' | Nuevo Score: 0.2121 | Tamaños N: [1738, 181]
  -> + Variable 13: 'monocitos_abs' | Nuevo Score: 0.2057 | Tamaños N: [1712, 207]
  -> + Variable 14: 'leucocitos_totales' | Nuevo Score: 0.2015 | Tamaños N: [1704, 215]
  -> + Variable 15: 'linfocitos_abs' | Nuevo Score: 0.1956 | Tamaños N: [1704, 215]
  -> + Variable 16: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.1856 | Tamaños N: [1706, 213]
  -> + Variable 17: 'hdl_mmol_l' | Nuevo Score: 0.1787 | Tamaños N: [1697, 222]
  -> + Variable 18: 'edad_an' | Nuevo Score: 0.1563 | Tamaños N: [1669, 250]
  -> + Variable 19: 'conc_hemoglobina_media' | Nuevo Score: 0.1556 | Tamaños N: [1650, 269]
  -> + Variable 20: 'largo_brazo_superior_cm' | Nuevo Score: 0.1501 | Tamaños N: [1648, 271]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('ratio_albumina_creatinina', 'ancho_distribucion_eritrocitos') (Score: 0.5285) | Tamaños N: [1571, 163, 185]
  -> + Variable 3: 'volumen_corpuscular_medio' | Nuevo Score: 0.4562 | Tamaños N: [165, 1583, 171]
  -> + Variable 4: 'plomo_sangre_umol_l' | Nuevo Score: 0.4111 | Tamaños N: [169, 199, 1551]
  -> + Variable 5: 'rigidez_mediana_kpa' | Nuevo Score: 0.3647 | Tamaños N: [165, 259, 1495]
  -> + Variable 6: 'conc_hemoglobina_media' | Nuevo Score: 0.3300 | Tamaños N: [251, 178, 1490]
  -> + Variable 7: 'selenio_sangre_umol_l' | Nuevo Score: 0.3004 | Tamaños N: [267, 178, 1474]
  -> + Variable 8: 'hemoglobina_g_dl' | Nuevo Score: 0.2760 | Tamaños N: [1469, 194, 256]
  -> + Variable 9: 'volumen_plaquetario_medio' | Nuevo Score: 0.2484 | Tamaños N: [1463, 201, 255]
  -> + Variable 10: 'ratio_pobreza' | Nuevo Score: 0.2256 | Tamaños N: [1466, 193, 260]
  -> + Variable 11: 'plaquetas_totales' | Nuevo Score: 0.2135 | Tamaños N: [1467, 259, 193]
  -> + Variable 12: 'eosinofilos_abs' | Nuevo Score: 0.1907 | Tamaños N: [1402, 258, 259]
  -> + Variable 13: 'imc' | Nuevo Score: 0.1828 | Tamaños N: [266, 255, 1398]
  -> + Variable 14: 'edad_an' | Nuevo Score: 0.1638 | Tamaños N: [343, 190, 1386]
  -> + Variable 15: 'cap_mediana_db_m' | Nuevo Score: 0.1589 | Tamaños N: [258, 1389, 272]
  -> + Variable 16: 'monocitos_abs' | Nuevo Score: 0.1527 | Tamaños N: [261, 1381, 277]
  -> + Variable 17: 'largo_brazo_superior_cm' | Nuevo Score: 0.1463 | Tamaños N: [272, 263, 1384]
  -> + Variable 18: 'cap_iqr' | Nuevo Score: 0.1415 | Tamaños N: [276, 248, 1395]
  -> + Variable 19: 'tamano_hogar' | Nuevo Score: 0.1365 | Tamaños N: [257, 264, 1398]
  -> + Variable 20: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.1307 | Tamaños N: [269, 259, 1391]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('creatinina_orina_umol_l', 'ratio_albumina_creatinina') (Score: 0.4514) | Tamaños N: [1095, 364, 324, 136]
  -> + Variable 3: 'plomo_sangre_umol_l' | Nuevo Score: 0.3349 | Tamaños N: [1264, 217, 363, 75]
  -> + Variable 4: 'rigidez_mediana_kpa' | Nuevo Score: 0.2620 | Tamaños N: [1304, 162, 130, 323]
  -> + Variable 5: 'conc_hemoglobina_media' | Nuevo Score: 0.2023 | Tamaños N: [1187, 426, 72, 234]
  -> + Variable 6: 'volumen_plaquetario_medio' | Nuevo Score: 0.1569 | Tamaños N: [1130, 522, 201, 66]
  -> + Variable 7: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.1313 | Tamaños N: [1127, 469, 155, 168]
  -> + Variable 8: 'volumen_corpuscular_medio' | Nuevo Score: 0.1167 | Tamaños N: [1124, 467, 179, 149]
  -> + Variable 9: 'edad_an' | Nuevo Score: 0.1055 | Tamaños N: [673, 844, 223, 179]
  -> + Variable 10: 'hdl_mmol_l' | Nuevo Score: 0.1211 | Tamaños N: [290, 184, 264, 1181]
  -> + Variable 11: 'imc' | Nuevo Score: 0.1076 | Tamaños N: [310, 174, 1158, 277]
  -> + Variable 12: 'selenio_sangre_umol_l' | Nuevo Score: 0.1046 | Tamaños N: [321, 1164, 184, 250]
  -> + Variable 13: 'eritrocitos_totales' | Nuevo Score: 0.1025 | Tamaños N: [1190, 270, 271, 188]
  -> + Variable 14: 'monocitos_abs' | Nuevo Score: 0.0944 | Tamaños N: [1178, 280, 190, 271]
  -> + Variable 15: 'ratio_pobreza' | Nuevo Score: 0.0867 | Tamaños N: [291, 266, 192, 1170]
  -> + Variable 16: 'cap_iqr' | Nuevo Score: 0.0827 | Tamaños N: [256, 205, 276, 1182]
  -> + Variable 17: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.0786 | Tamaños N: [260, 189, 297, 1173]
  -> + Variable 18: 'plaquetas_totales' | Nuevo Score: 0.0721 | Tamaños N: [260, 209, 290, 1160]
  -> + Variable 19: 'eosinofilos_abs' | Nuevo Score: 0.0638 | Tamaños N: [1101, 318, 202, 298]
  -> + Variable 20: 'pulso' | Nuevo Score: 0.0577 | Tamaños N: [1109, 321, 194, 295]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tamano_hogar', 'eosinofilos_abs') (Score: 0.4500) | Tamaños N: [175, 810, 173, 257, 504]
  -> + Variable 3: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.2968 | Tamaños N: [243, 160, 97, 517, 902]
  -> + Variable 4: 'ratio_albumina_creatinina' | Nuevo Score: 0.2129 | Tamaños N: [236, 507, 253, 851, 72]
  -> + Variable 5: 'tiempo_seg_cond4' | Nuevo Score: 0.1684 | Tamaños N: [988, 143, 156, 563, 69]
  -> + Variable 6: 'pulso' | Nuevo Score: 0.1324 | Tamaños N: [987, 575, 154, 142, 61]
  -> + Variable 7: 'ldl_martin_mmol_l' | Nuevo Score: 0.1110 | Tamaños N: [987, 568, 152, 141, 71]
  -> + Variable 8: 'rigidez_mediana_kpa' | Nuevo Score: 0.0933 | Tamaños N: [978, 120, 181, 571, 69]
  -> + Variable 9: 'linfocitos_abs' | Nuevo Score: 0.0830 | Tamaños N: [980, 101, 587, 158, 93]
  -> + Variable 10: 'hemoglobina_g_dl' | Nuevo Score: 0.0769 | Tamaños N: [89, 99, 152, 603, 976]
  -> + Variable 11: 'volumen_plaquetario_medio' | Nuevo Score: 0.0676 | Tamaños N: [83, 602, 150, 975, 109]
  -> + Variable 12: 'peso_flebotomia' | Nuevo Score: 0.0568 | Tamaños N: [99, 569, 181, 91, 979]
  -> + Variable 13: 'manganeso_sangre_nmol_l' | Nuevo Score: 0.0434 | Tamaños N: [976, 124, 215, 487, 117]
  -> + Variable 14: 'eritrocitos_totales' | Nuevo Score: 0.0429 | Tamaños N: [89, 235, 968, 487, 140]
  -> + Variable 15: 'plomo_sangre_umol_l' | Nuevo Score: 0.0424 | Tamaños N: [78, 965, 615, 73, 188]
  -> + Variable 16: 'largo_pierna_superior_cm' | Nuevo Score: 0.0383 | Tamaños N: [85, 961, 124, 157, 592]
  -> + Variable 17: 'conc_hemoglobina_media' | Nuevo Score: 0.0332 | Tamaños N: [959, 161, 571, 124, 104]
  -> + Variable 18: 'volumen_corpuscular_medio' | Nuevo Score: 0.0335 | Tamaños N: [116, 588, 159, 950, 106]
  -> + Variable 19: 'leucocitos_totales' | Nuevo Score: 0.0359 | Tamaños N: [181, 675, 143, 755, 165]
  -> + Variable 20: 'imc' | Nuevo Score: 0.0327 | Tamaños N: [755, 143, 220, 637, 164]

================================================================================
🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆
================================================================================

🌟 EL CAMPEÓN ABSOLUTO:
  -> K Óptimo: 2
  -> Silhouette Score Máximo: 0.5880
  -> Distribución de Pacientes (N): [1794, 125]
  -> Variables óptimas (2): plomo_sangre_umol_l, selenio_sangre_umol_l

--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---

Para K=2:
  -> Silhouette Score: 0.5880
  -> Distribución de Pacientes (N): [1794, 125]
  -> N Variables: 2
  -> Variables: plomo_sangre_umol_l, selenio_sangre_umol_l

Para K=3:
  -> Silhouette Score: 0.5285
  -> Distribución de Pacientes (N): [1571, 163, 185]
  -> N Variables: 2
  -> Variables: ratio_albumina_creatinina, ancho_distribucion_eritrocitos

Para K=4:
  -> Silhouette Score: 0.4514
  -> Distribución de Pacientes (N): [1095, 364, 324, 136]
  -> N Variables: 2
  -> Variables: creatinina_orina_umol_l, ratio_albumina_creatinina

Para K=5:
  -> Silhouette Score: 0.4500
  -> Distribución de Pacientes (N): [175, 810, 173, 257, 504]
  -> N Variables: 2
  -> Variables: tamano_hogar, eosinofilos_abs

In [15]:
#comando de LIMPIEZA DE KERNEL PARA EVITAR QUE SE MEZCLEN VARIBALES DE DISTINTAS PRUEBAS
%reset -f
%reset -f in out dhist

Flushing input history
Flushing output cache (0 entries)
Flushing directory history

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------

### Clustering con variables del codigo genético.

In [1]:
import pandas as pd
from sklearn.cluster import KMeans
from kmodes.kprototypes import KPrototypes
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import unicodedata
import re
import gower

import kmedoids # Nueva librería para PAM
from sklearn.cluster import AgglomerativeClustering
from sklearn.mixture import GaussianMixture

from scipy.cluster.hierarchy import dendrogram, linkage
import scipy.spatial.distance as ssd
import prince
import numpy as np

from itertools import combinations
import heapq
from sklearn.preprocessing import StandardScaler

In [2]:
trainset = pd.read_csv("train_imputado.csv")

In [3]:
trainset.head(10)

,edad_an,tamano_hogar,psu,ratio_pobreza,tiempo_seg_cond1,tiempo_seg_cond2,tiempo_seg_cond3,tiempo_seg_cond4,pulso,peso_kg,...,elegibilidad_balance,convulsiones,caidas,fracturas,medicacion_osteoporosis,aprueba_cond4,tamano_manguito_pa,estado_elastografia,tipo_sonda_elasto,raza_etnia
0,46.0,5.0,2.0,4.62,15.0,15.0,30.0,30.0,66.0,111.6,...,1,0,0,0,0,1,4.0,1,b'XL',3.0
1,57.0,3.0,2.0,2.17,15.0,15.0,30.0,30.0,73.0,124.1,...,1,0,0,0,0,1,4.0,1,b'XL',3.0
2,48.0,3.0,2.0,5.00,15.0,15.0,30.0,30.0,67.0,89.3,...,0,0,0,1,0,1,4.0,1,b'M',3.0
3,40.0,5.0,1.0,3.11,15.0,15.0,30.0,30.0,81.0,81.9,...,1,0,0,0,0,1,3.0,1,b'M',2.0
4,66.0,3.0,2.0,3.47,15.0,15.0,30.0,8.0,103.0,77.4,...,1,0,0,0,0,0,3.0,1,b'M',6.0
5,27.0,2.0,1.0,5.00,15.0,15.0,30.0,30.0,69.0,50.8,...,1,0,0,0,0,1,3.0,1,b'M',7.0
6,69.0,1.0,1.0,2.43,15.0,15.0,30.0,30.0,50.0,86.4,...,1,0,0,0,0,1,4.0,1,b'XL',3.0
7,33.0,5.0,2.0,1.05,15.0,15.0,30.0,30.0,58.0,84.2,...,1,0,0,0,0,1,3.0,1,b'M',3.0
8,54.0,4.0,1.0,5.00,15.0,15.0,30.0,22.0,73.0,94.2,...,1,0,0,0,0,1,4.0,1,b'XL',3.0
9,40.0,1.0,1.0,5.00,15.0,15.0,30.0,2.0,51.0,66.5,...,1,0,0,0,0,0,3.0,1,b'M',3.0

In [4]:
# 1. Cargar diccionario



ruta_diccionario = "../data/Diccionario_TFM_CompletoMF.xlsx"
diccionario = pd.read_excel(ruta_diccionario)

def normalizar_texto(x):
    x = str(x).strip().lower()
    x = unicodedata.normalize("NFKD", x).encode("ascii", "ignore").decode("utf-8")
    return x

def limpiar_nombre(col):
    col = col.lower()
    col = col.replace(" ", "_")
    col = re.sub(r'[^a-z0-9_]', '', col)
    return col

diccionario["Tipo de Variable"] = diccionario["Tipo de Variable"].apply(normalizar_texto)

cols_categoricas = diccionario.loc[
    diccionario["Tipo de Variable"].str.contains("categ", na=False), "Qué es"
].tolist()
var_categoricas = [col for col in cols_categoricas if col in trainset.columns]

cols_numericas = diccionario.loc[
    diccionario["Tipo de Variable"].str.contains("num", na=False), "Qué es"
].tolist()
var_numericas = [col for col in cols_numericas if col in trainset.columns]

trainset[var_numericas] = trainset[var_numericas].astype('float64')
trainset[var_categoricas] = trainset[var_categoricas].astype('object')

print(f"Número de columnas categóricas: {len(var_categoricas)}")
print(var_categoricas)

print(f"Número de columnas numéricas: {len(var_numericas)}")
print(var_numericas)

Número de columnas categóricas: 16
['genero', 'periodo_examen', 'pais_nacimiento', 'toma_suplementos', 'toma_antiacidos', 'estado_examen_balance', 'elegibilidad_balance', 'convulsiones', 'caidas', 'fracturas', 'medicacion_osteoporosis', 'aprueba_cond4', 'tamano_manguito_pa', 'estado_elastografia', 'tipo_sonda_elasto', 'raza_etnia']
Número de columnas numéricas: 46
['edad_an', 'tamano_hogar', 'psu', 'ratio_pobreza', 'tiempo_seg_cond1', 'tiempo_seg_cond2', 'tiempo_seg_cond3', 'tiempo_seg_cond4', 'pulso', 'peso_kg', 'altura_cm', 'imc', 'largo_pierna_superior_cm', 'largo_brazo_superior_cm', 'medidas_validas_elasto', 'intentos_totales_elasto', 'rigidez_mediana_kpa', 'rigidez_iqr', 'ratio_iqr_mediana', 'cap_mediana_db_m', 'cap_iqr', 'albumina_orina_mg_l', 'creatinina_orina_umol_l', 'ratio_albumina_creatinina', 'peso_flebotomia', 'proteina_c_reactiva_mg_l', 'leucocitos_totales', 'linfocitos_abs', 'monocitos_abs', 'neutrofilos_abs', 'eosinofilos_abs', 'eritrocitos_totales', 'hemoglobina_g_dl', 'volumen_corpuscular_medio', 'conc_hemoglobina_media', 'ancho_distribucion_eritrocitos', 'plaquetas_totales', 'volumen_plaquetario_medio', 'trigliceridos_mmol_l', 'ldl_martin_mmol_l', 'hdl_mmol_l', 'plomo_sangre_umol_l', 'cadmio_sangre_nmol_l', 'mercurio_sangre_nmol_l', 'selenio_sangre_umol_l', 'manganeso_sangre_nmol_l']

eliminamos las mismas variables que en el apartado anterior

In [5]:
columnas_a_eliminar = ['tiempo_seg_cond1', 'tiempo_seg_cond2', 'tiempo_seg_cond3',  'albumina_orina_mg_l', 'neutrofilos_abs','rigidez_iqr', 'ratio_iqr_mediana','medidas_validas_elasto','intentos_totales_elasto','psu']

# Utilizamos el método .drop() especificando que queremos eliminar columnas
trainset = trainset.drop(columns=columnas_a_eliminar)
trainset.shape

(1919, 52)

In [6]:
var_num = trainset.select_dtypes(include=['number'])
var_num.shape

(1919, 36)

obtenemos el skew para cada variable: medida estadística que describe la falta de simetría en la distribución de tus datos alrededor de su media.

In [7]:
asimetria = var_num.skew().sort_values(ascending=False)

print("--- Nivel de Asimetría (Skewness) de las Variables ---")
print("Valores ideales: entre -1 y 1. Valores > 1 o < -1 indican asimetría severa.\n")
print(asimetria)

--- Nivel de Asimetría (Skewness) de las Variables ---
Valores ideales: entre -1 y 1. Valores > 1 o < -1 indican asimetría severa.

plomo_sangre_umol_l               19.482658
ratio_albumina_creatinina         14.215589
rigidez_mediana_kpa                7.974745
proteina_c_reactiva_mg_l           6.952438
trigliceridos_mmol_l               6.916607
cadmio_sangre_nmol_l               5.434901
eosinofilos_abs                    5.417549
selenio_sangre_umol_l              5.352683
ancho_distribucion_eritrocitos     5.211623
mercurio_sangre_nmol_l             4.743745
cap_iqr                            1.838814
peso_flebotomia                    1.829170
manganeso_sangre_nmol_l            1.501256
creatinina_orina_umol_l            1.216544
monocitos_abs                      1.209084
linfocitos_abs                     1.156344
imc                                1.138741
leucocitos_totales                 1.137664
hdl_mmol_l                         1.131395
peso_kg                            0.973787
tamano_hogar                       0.884210
plaquetas_totales                  0.787695
volumen_plaquetario_medio          0.648152
pulso                              0.533362
ldl_martin_mmol_l                  0.386823
eritrocitos_totales                0.346634
largo_brazo_superior_cm            0.163264
altura_cm                          0.147654
cap_mediana_db_m                   0.081952
largo_pierna_superior_cm           0.006313
ratio_pobreza                     -0.176222
hemoglobina_g_dl                  -0.242129
edad_an                           -0.293307
conc_hemoglobina_media            -0.387832
tiempo_seg_cond4                  -0.744717
volumen_corpuscular_medio         -0.815809
dtype: float64

se puede observar que para ciertas variables la transformación logaritmica no será sido del todo útil esto es debido a:

1. medidas como plomo_sangre_umol_l son muy pequeñas y la la función log1p(x) uma 1 antes de sacar el logaritmo por tanto si se le suma 1 a un valor muy pequeño es practicamnete 1.

Para estos valores se aplica la transformación de raiz cuadrada.

In [8]:
skew_actual = var_num.skew()
var_num_log = var_num.copy()

# 2. Filtrar las variables con asimetría severa
variables_sesgadas = skew_actual[skew_actual.abs() > 1].index.tolist()

print("--- VARIABLES DETECTADAS PARA TRANSFORMACIÓN ---")
for col in variables_sesgadas:
    print(f"- {col} (Skew original: {skew_actual[col]:.2f})")

# Definimos las variables rebeldes que necesitan raíz cuadrada en lugar de logaritmo
variables_raiz = ['plomo_sangre_umol_l']

print("\n--- APLICANDO TRANSFORMACIONES ---")
# 3. Aplicar la transformación (Logaritmo o Raíz Cuadrada)
for col in variables_sesgadas:
    # Si la variable está en nuestra lista de excepciones, aplicamos raíz cuadrada
    if col in variables_raiz:
        var_num_log[col] = np.sqrt(var_num_log[col])
        print(f"✓ Raíz cuadrada aplicada a: {col}")
    else:
        # Para el resto, verificamos que no haya valores negativos antes de aplicar el logaritmo
        if (var_num_log[col] < 0).any():
            print(f"⚠️ Advertencia: {col} tiene valores negativos. No se aplicó logaritmo.")
        else:
            var_num_log[col] = np.log1p(var_num_log[col])
            # print(f"✓ Logaritmo aplicado a: {col}") # Opcional: descomentar para ver el progreso

print("\nTransformaciones aplicadas con éxito.")

# 4. Verificar los nuevos niveles de asimetría para confirmar la mejora
print("\n--- NUEVA ASIMETRÍA TRAS LAS TRANSFORMACIONES ---")
skew_nuevo = var_num_log[variables_sesgadas].skew()
for col in variables_sesgadas:
    print(f"- {col} (Nuevo Skew: {skew_nuevo[col]:.2f})")

--- VARIABLES DETECTADAS PARA TRANSFORMACIÓN ---
- imc (Skew original: 1.14)
- rigidez_mediana_kpa (Skew original: 7.97)
- cap_iqr (Skew original: 1.84)
- creatinina_orina_umol_l (Skew original: 1.22)
- ratio_albumina_creatinina (Skew original: 14.22)
- peso_flebotomia (Skew original: 1.83)
- proteina_c_reactiva_mg_l (Skew original: 6.95)
- leucocitos_totales (Skew original: 1.14)
- linfocitos_abs (Skew original: 1.16)
- monocitos_abs (Skew original: 1.21)
- eosinofilos_abs (Skew original: 5.42)
- ancho_distribucion_eritrocitos (Skew original: 5.21)
- trigliceridos_mmol_l (Skew original: 6.92)
- hdl_mmol_l (Skew original: 1.13)
- plomo_sangre_umol_l (Skew original: 19.48)
- cadmio_sangre_nmol_l (Skew original: 5.43)
- mercurio_sangre_nmol_l (Skew original: 4.74)
- selenio_sangre_umol_l (Skew original: 5.35)
- manganeso_sangre_nmol_l (Skew original: 1.50)

--- APLICANDO TRANSFORMACIONES ---
✓ Raíz cuadrada aplicada a: plomo_sangre_umol_l

Transformaciones aplicadas con éxito.

--- NUEVA ASIMETRÍA TRAS LAS TRANSFORMACIONES ---
- imc (Nuevo Skew: 0.42)
- rigidez_mediana_kpa (Nuevo Skew: 2.00)
- cap_iqr (Nuevo Skew: -0.26)
- creatinina_orina_umol_l (Nuevo Skew: -0.72)
- ratio_albumina_creatinina (Nuevo Skew: 1.66)
- peso_flebotomia (Nuevo Skew: 0.10)
- proteina_c_reactiva_mg_l (Nuevo Skew: 1.02)
- leucocitos_totales (Nuevo Skew: 0.23)
- linfocitos_abs (Nuevo Skew: 0.22)
- monocitos_abs (Nuevo Skew: 0.72)
- eosinofilos_abs (Nuevo Skew: 2.57)
- ancho_distribucion_eritrocitos (Nuevo Skew: 2.85)
- trigliceridos_mmol_l (Nuevo Skew: 1.56)
- hdl_mmol_l (Nuevo Skew: 0.57)
- plomo_sangre_umol_l (Nuevo Skew: 4.32)
- cadmio_sangre_nmol_l (Nuevo Skew: 1.28)
- mercurio_sangre_nmol_l (Nuevo Skew: 0.76)
- selenio_sangre_umol_l (Nuevo Skew: 1.85)
- manganeso_sangre_nmol_l (Nuevo Skew: 0.27)

In [9]:

scaler = StandardScaler()
datos_escalados_array = scaler.fit_transform(var_num_log)

In [10]:
var_num_log_scaled = pd.DataFrame(
    datos_escalados_array,
    columns=var_num_log.columns, # Recuperamos los nombres de las columnas
    index=var_num_log.index      # Recuperamos los índices originales
)
var_num_log_scaled.head(10)

,edad_an,tamano_hogar,ratio_pobreza,tiempo_seg_cond4,pulso,peso_kg,altura_cm,imc,largo_pierna_superior_cm,largo_brazo_superior_cm,...,plaquetas_totales,volumen_plaquetario_medio,trigliceridos_mmol_l,ldl_martin_mmol_l,hdl_mmol_l,plomo_sangre_umol_l,cadmio_sangre_nmol_l,mercurio_sangre_nmol_l,selenio_sangre_umol_l,manganeso_sangre_nmol_l
0,-0.188751,1.575278,0.984181,0.810059,-0.438261,1.282766,-1.541547,2.237715,-0.965813,-1.984451,...,-0.148788,-0.064880,-0.217923,0.564297,0.991320,-1.128475,-0.198237,0.910452,0.358438,0.143478
1,0.575265,0.208042,-0.578577,0.810059,0.158633,1.859173,-0.490585,2.124402,-1.332158,-0.759037,...,1.324984,-1.395746,2.836066,-0.674377,-1.076357,-0.913991,0.978343,-1.202643,-0.554631,-2.931749
2,-0.049839,0.208042,1.226568,0.810059,-0.352991,0.254454,0.621010,0.084882,0.922273,0.641436,...,-1.146655,0.933270,-0.629579,0.004270,0.050606,-0.913991,0.038614,-0.144919,0.328263,1.263090
3,-0.605487,1.575278,0.021012,0.810059,0.840797,-0.086779,1.136385,-0.556256,1.485880,0.816495,...,-0.440472,0.489648,-0.113511,1.921592,0.050606,0.263839,-0.290164,1.259538,0.298000,-0.321799
4,1.200370,0.208042,0.250642,-1.268443,2.716750,-0.294286,0.378480,-0.420615,0.302304,0.606424,...,-0.302306,-1.395746,1.260745,-1.470505,0.742922,2.202996,3.421947,3.363510,3.024857,0.752001
5,-1.508416,-0.475576,1.226568,0.810059,-0.182450,-1.520881,-1.460704,-1.282279,-1.163075,-1.669345,...,-0.102733,1.376892,-1.218732,-1.323370,1.641699,16.169732,0.345159,-0.976735,0.972513,1.507047
6,1.408738,-1.159194,-0.412733,0.810059,-1.802591,0.120728,-0.965539,0.777208,-0.655829,-0.513955,...,-0.271603,0.156931,-0.670505,-0.762202,0.537385,0.318915,0.906603,-0.011673,-0.488996,0.709928
7,-1.091680,1.575278,-1.292981,0.810059,-1.120426,0.019280,0.216793,0.024675,0.247010,0.180119,...,0.588098,-0.619407,0.523314,0.291392,-0.394170,0.091336,-0.454188,-0.947824,0.328263,-0.478391
8,0.366897,0.891660,1.226568,0.054240,0.158633,0.480406,0.348164,0.457969,-0.148582,-0.513955,...,-0.087381,-0.952124,2.461369,-0.142865,-1.142999,-0.159167,-0.518173,-0.024319,-0.521761,-1.554410
9,-0.605487,-1.159194,1.226568,-1.835307,-1.717320,-0.796913,0.732169,-1.262144,0.386845,0.116258,...,-0.732157,-0.064880,-1.170429,-1.027958,-0.265184,0.603880,-0.814587,1.384638,1.224884,-2.172327

In [11]:
var_num_log_scaled.shape

(1919, 36)

In [12]:


columnas_genetico_numericas = [
    "largo_brazo_superior_cm",
    "mercurio_sangre_nmol_l",
    "hdl_mmol_l",
    "creatinina_orina_umol_l",
    "hemoglobina_g_dl",
    "peso_kg",
    "volumen_plaquetario_medio",
    "ancho_distribucion_eritrocitos",
    "conc_hemoglobina_media",
    "tamano_hogar",
    "pulso",
    "plaquetas_totales",
    "edad_an",
    "trigliceridos_mmol_l"
]

Var_num_log_scaled_original = var_num_log_scaled.copy()
var_num_log_scaled = var_num_log_scaled[columnas_genetico_numericas]
var_num_log_scaled.shape

(1919, 14)

In [13]:
var_num_log_scaled.head()

,largo_brazo_superior_cm,mercurio_sangre_nmol_l,hdl_mmol_l,creatinina_orina_umol_l,hemoglobina_g_dl,peso_kg,volumen_plaquetario_medio,ancho_distribucion_eritrocitos,conc_hemoglobina_media,tamano_hogar,pulso,plaquetas_totales,edad_an,trigliceridos_mmol_l
0,-1.984451,0.910452,0.991320,0.853000,-0.687034,1.282766,-0.064880,0.335281,0.434668,1.575278,-0.438261,-0.148788,-0.188751,-0.217923
1,-0.759037,-1.202643,-1.076357,-0.631893,-1.107096,1.859173,-1.395746,1.460799,-3.080375,0.208042,0.158633,1.324984,0.575265,2.836066
2,0.641436,-0.144919,0.050606,1.006903,-0.196961,0.254454,0.933270,-0.624857,0.786172,0.208042,-0.352991,-1.146655,-0.049839,-0.629579
3,0.816495,1.259538,0.050606,1.074952,0.433133,-0.086779,0.489648,-0.267257,-0.385509,1.575278,0.840797,-0.440472,-0.605487,-0.113511
4,0.606424,3.363510,0.742922,0.125142,-0.126951,-0.294286,-1.395746,1.383632,-0.502677,0.208042,2.716750,-0.302306,1.200370,1.260745

K-Means

In [14]:
print("=" * 80)
print("FORWARD SELECTION CON TAMAÑO DE CLÚSTERES (N)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 14    # Límite máximo de variables a agrupar
columnas_totales = var_num_log_scaled.columns.tolist()

resultados_finales = {}
campeon_global_score = -1
campeon_global_k = -1
campeon_global_vars = []
campeon_global_conteos = []

for k in rango_k:
    print(f"\n[ Iniciando búsqueda para K={k} ]")

    columnas_disponibles = columnas_totales.copy()
    variables_seleccionadas = []

    # --- PASO 1: Buscar el mejor PAR inicial (La base sólida) ---
    mejor_score_par = -1
    mejor_par = ()
    mejor_labels_par = None

    # Probamos las parejas posibles
    for combo in combinations(columnas_disponibles, 2):
        X_subset = var_num_log_scaled[list(combo)]
        kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
        labels = kmeans.fit_predict(X_subset)
        score = silhouette_score(X_subset, labels)

        if score > mejor_score_par:
            mejor_score_par = score
            mejor_par = combo
            mejor_labels_par = labels # Guardamos las etiquetas ganadoras

    # Fijamos el mejor par y lo sacamos de las disponibles
    variables_seleccionadas.extend(mejor_par)
    for var in mejor_par:
        columnas_disponibles.remove(var)

    # Calculamos N por clúster
    conteos_par = np.bincount(mejor_labels_par).tolist()

    print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

    # Guardamos el historial de scores y conteos
    historial_scores = [mejor_score_par]
    historial_conteos = [conteos_par]

    # --- PASO 2: Forward Selection (Añadir 1 a 1 hasta max_variables) ---
    for paso in range(3, max_variables + 1):
        mejor_score_paso = -1
        mejor_variable_paso = None
        mejor_labels_paso = None

        # Probamos a añadir cada una de las variables que quedan libres
        for var_candidata in columnas_disponibles:
            features_a_probar = variables_seleccionadas + [var_candidata]
            X_subset = var_num_log_scaled[features_a_probar]

            kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
            labels = kmeans.fit_predict(X_subset)
            score = silhouette_score(X_subset, labels)

            if score > mejor_score_paso:
                mejor_score_paso = score
                mejor_variable_paso = var_candidata
                mejor_labels_paso = labels # Guardamos las etiquetas ganadoras

        # Consolidamos la variable ganadora de este paso
        variables_seleccionadas.append(mejor_variable_paso)
        columnas_disponibles.remove(mejor_variable_paso)

        # Calculamos N por clúster
        conteos_paso = np.bincount(mejor_labels_paso).tolist()

        historial_scores.append(mejor_score_paso)
        historial_conteos.append(conteos_paso)

        print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

    # --- PASO 3: Encontrar el pico máximo para este K ---
    indice_mejor_momento = historial_scores.index(max(historial_scores))
    score_pico = historial_scores[indice_mejor_momento]
    conteos_pico = historial_conteos[indice_mejor_momento]

    # El índice 0 equivale a 2 variables, índice 1 a 3 variables, etc.
    vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

    resultados_finales[k] = {
        'score': score_pico,
        'variables': vars_en_pico,
        'conteos': conteos_pico
    }

    # Actualizar campeón global absoluto
    if score_pico > campeon_global_score:
        campeon_global_score = score_pico
        campeon_global_k = k
        campeon_global_vars = vars_en_pico
        campeon_global_conteos = conteos_pico

print("\n" + "=" * 80)
print("🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆")
print("=" * 80)

print(f"\n🌟 EL CAMPEÓN ABSOLUTO:")
print(f"  -> K Óptimo: {campeon_global_k}")
print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
print(f"  -> Distribución de Pacientes (N): {campeon_global_conteos}")
print(f"  -> Variables óptimas ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

print("\n--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---")
for k in rango_k:
    res = resultados_finales[k]
    print(f"\nPara K={k}:")
    print(f"  -> Silhouette Score: {res['score']:.4f}")
    print(f"  -> Distribución de Pacientes (N): {res['conteos']}")
    print(f"  -> N Variables: {len(res['variables'])}")
    print(f"  -> Variables: {', '.join(res['variables'])}")

================================================================================
FORWARD SELECTION CON TAMAÑO DE CLÚSTERES (N)
================================================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('hemoglobina_g_dl', 'ancho_distribucion_eritrocitos') (Score: 0.4765) | Tamaños N: [1590, 329]
  -> + Variable 3: 'pulso' | Nuevo Score: 0.3565 | Tamaños N: [1589, 330]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.2931 | Tamaños N: [1598, 321]
  -> + Variable 5: 'peso_kg' | Nuevo Score: 0.2521 | Tamaños N: [1509, 410]
  -> + Variable 6: 'tamano_hogar' | Nuevo Score: 0.2192 | Tamaños N: [1518, 401]
  -> + Variable 7: 'conc_hemoglobina_media' | Nuevo Score: 0.1897 | Tamaños N: [1391, 528]
  -> + Variable 8: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.1670 | Tamaños N: [1385, 534]
  -> + Variable 9: 'plaquetas_totales' | Nuevo Score: 0.1552 | Tamaños N: [559, 1360]
  -> + Variable 10: 'edad_an' | Nuevo Score: 0.1344 | Tamaños N: [1329, 590]
  -> + Variable 11: 'hdl_mmol_l' | Nuevo Score: 0.1144 | Tamaños N: [1230, 689]
  -> + Variable 12: 'largo_brazo_superior_cm' | Nuevo Score: 0.1094 | Tamaños N: [923, 996]
  -> + Variable 13: 'trigliceridos_mmol_l' | Nuevo Score: 0.1061 | Tamaños N: [938, 981]
  -> + Variable 14: 'creatinina_orina_umol_l' | Nuevo Score: 0.1026 | Tamaños N: [949, 970]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'edad_an') (Score: 0.4788) | Tamaños N: [792, 930, 197]
  -> + Variable 3: 'tamano_hogar' | Nuevo Score: 0.3551 | Tamaños N: [843, 914, 162]
  -> + Variable 4: 'conc_hemoglobina_media' | Nuevo Score: 0.2790 | Tamaños N: [801, 232, 886]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.2317 | Tamaños N: [780, 257, 882]
  -> + Variable 6: 'trigliceridos_mmol_l' | Nuevo Score: 0.1942 | Tamaños N: [881, 760, 278]
  -> + Variable 7: 'plaquetas_totales' | Nuevo Score: 0.1680 | Tamaños N: [777, 875, 267]
  -> + Variable 8: 'hdl_mmol_l' | Nuevo Score: 0.1478 | Tamaños N: [875, 246, 798]
  -> + Variable 9: 'peso_kg' | Nuevo Score: 0.1335 | Tamaños N: [769, 870, 280]
  -> + Variable 10: 'largo_brazo_superior_cm' | Nuevo Score: 0.1360 | Tamaños N: [811, 836, 272]
  -> + Variable 11: 'pulso' | Nuevo Score: 0.1242 | Tamaños N: [795, 850, 274]
  -> + Variable 12: 'creatinina_orina_umol_l' | Nuevo Score: 0.1179 | Tamaños N: [265, 825, 829]
  -> + Variable 13: 'volumen_plaquetario_medio' | Nuevo Score: 0.1079 | Tamaños N: [820, 820, 279]
  -> + Variable 14: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.0989 | Tamaños N: [818, 781, 320]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'edad_an') (Score: 0.4449) | Tamaños N: [767, 798, 307, 47]
  -> + Variable 3: 'trigliceridos_mmol_l' | Nuevo Score: 0.3522 | Tamaños N: [300, 773, 697, 149]
  -> + Variable 4: 'tamano_hogar' | Nuevo Score: 0.2718 | Tamaños N: [449, 821, 501, 148]
  -> + Variable 5: 'conc_hemoglobina_media' | Nuevo Score: 0.2220 | Tamaños N: [271, 731, 703, 214]
  -> + Variable 6: 'plaquetas_totales' | Nuevo Score: 0.1856 | Tamaños N: [288, 216, 718, 697]
  -> + Variable 7: 'hemoglobina_g_dl' | Nuevo Score: 0.1654 | Tamaños N: [292, 760, 218, 649]
  -> + Variable 8: 'hdl_mmol_l' | Nuevo Score: 0.1414 | Tamaños N: [452, 632, 624, 211]
  -> + Variable 9: 'peso_kg' | Nuevo Score: 0.1255 | Tamaños N: [522, 575, 225, 597]
  -> + Variable 10: 'largo_brazo_superior_cm' | Nuevo Score: 0.1176 | Tamaños N: [555, 597, 211, 556]
  -> + Variable 11: 'creatinina_orina_umol_l' | Nuevo Score: 0.1122 | Tamaños N: [540, 638, 200, 541]
  -> + Variable 12: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.1005 | Tamaños N: [529, 236, 541, 613]
  -> + Variable 13: 'pulso' | Nuevo Score: 0.0930 | Tamaños N: [523, 617, 543, 236]
  -> + Variable 14: 'volumen_plaquetario_medio' | Nuevo Score: 0.0815 | Tamaños N: [532, 605, 388, 394]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tamano_hogar', 'edad_an') (Score: 0.4426) | Tamaños N: [362, 716, 348, 190, 303]
  -> + Variable 3: 'trigliceridos_mmol_l' | Nuevo Score: 0.3205 | Tamaños N: [206, 356, 218, 732, 407]
  -> + Variable 4: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.2806 | Tamaños N: [397, 232, 464, 135, 691]
  -> + Variable 5: 'conc_hemoglobina_media' | Nuevo Score: 0.2252 | Tamaños N: [452, 681, 380, 194, 212]
  -> + Variable 6: 'plaquetas_totales' | Nuevo Score: 0.1840 | Tamaños N: [227, 384, 683, 462, 163]
  -> + Variable 7: 'hemoglobina_g_dl' | Nuevo Score: 0.1553 | Tamaños N: [226, 695, 369, 429, 200]
  -> + Variable 8: 'creatinina_orina_umol_l' | Nuevo Score: 0.1356 | Tamaños N: [236, 577, 570, 196, 340]
  -> + Variable 9: 'hdl_mmol_l' | Nuevo Score: 0.1163 | Tamaños N: [418, 171, 502, 572, 256]
  -> + Variable 10: 'largo_brazo_superior_cm' | Nuevo Score: 0.1097 | Tamaños N: [238, 467, 518, 511, 185]
  -> + Variable 11: 'pulso' | Nuevo Score: 0.1015 | Tamaños N: [421, 508, 307, 181, 502]
  -> + Variable 12: 'peso_kg' | Nuevo Score: 0.0963 | Tamaños N: [320, 509, 503, 399, 188]
  -> + Variable 13: 'volumen_plaquetario_medio' | Nuevo Score: 0.0878 | Tamaños N: [331, 413, 507, 483, 185]
  -> + Variable 14: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.0797 | Tamaños N: [464, 496, 384, 412, 163]

================================================================================
🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆
================================================================================

🌟 EL CAMPEÓN ABSOLUTO:
  -> K Óptimo: 3
  -> Silhouette Score Máximo: 0.4788
  -> Distribución de Pacientes (N): [792, 930, 197]
  -> Variables óptimas (2): ancho_distribucion_eritrocitos, edad_an

--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---

Para K=2:
  -> Silhouette Score: 0.4765
  -> Distribución de Pacientes (N): [1590, 329]
  -> N Variables: 2
  -> Variables: hemoglobina_g_dl, ancho_distribucion_eritrocitos

Para K=3:
  -> Silhouette Score: 0.4788
  -> Distribución de Pacientes (N): [792, 930, 197]
  -> N Variables: 2
  -> Variables: ancho_distribucion_eritrocitos, edad_an

Para K=4:
  -> Silhouette Score: 0.4449
  -> Distribución de Pacientes (N): [767, 798, 307, 47]
  -> N Variables: 2
  -> Variables: ancho_distribucion_eritrocitos, edad_an

Para K=5:
  -> Silhouette Score: 0.4426
  -> Distribución de Pacientes (N): [362, 716, 348, 190, 303]
  -> N Variables: 2
  -> Variables: tamano_hogar, edad_an

Clustering Jerarquico (tras transofrmar y estandarizar)

In [15]:
import numpy as np
from itertools import combinations
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

print("=" * 80)
print("FORWARD SELECTION: CLUSTERING JERÁRQUICO CON TAMAÑO (N)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 14    # Límite máximo de variables a agrupar
columnas_totales = var_num_log_scaled.columns.tolist()

resultados_finales = {}
campeon_global_score = -1
campeon_global_k = -1
campeon_global_vars = []
campeon_global_conteos = []

for k in rango_k:
    print(f"\n[ Iniciando búsqueda para K={k} ]")

    columnas_disponibles = columnas_totales.copy()
    variables_seleccionadas = []

    # --- PASO 1: Buscar el mejor PAR inicial (La base sólida) ---
    mejor_score_par = -1
    mejor_par = ()
    mejor_labels_par = None

    # Probamos las parejas posibles
    for combo in combinations(columnas_disponibles, 2):
        X_subset = var_num_log_scaled[list(combo)]

        # INSTANCIAMOS EL CLUSTERING JERÁRQUICO
        jerarquico = AgglomerativeClustering(n_clusters=k, linkage='ward')
        labels = jerarquico.fit_predict(X_subset)
        score = silhouette_score(X_subset, labels)

        if score > mejor_score_par:
            mejor_score_par = score
            mejor_par = combo
            mejor_labels_par = labels # Guardamos las etiquetas ganadoras

    # Fijamos el mejor par y lo sacamos de las disponibles
    variables_seleccionadas.extend(mejor_par)
    for var in mejor_par:
        columnas_disponibles.remove(var)

    # Calculamos N por clúster
    conteos_par = np.bincount(mejor_labels_par).tolist()

    print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

    # Guardamos el historial de scores y conteos
    historial_scores = [mejor_score_par]
    historial_conteos = [conteos_par]

    # --- PASO 2: Forward Selection (Añadir 1 a 1 hasta max_variables) ---
    for paso in range(3, max_variables + 1):
        mejor_score_paso = -1
        mejor_variable_paso = None
        mejor_labels_paso = None

        # Probamos a añadir cada una de las variables que quedan libres
        for var_candidata in columnas_disponibles:
            features_a_probar = variables_seleccionadas + [var_candidata]
            X_subset = var_num_log_scaled[features_a_probar]

            # INSTANCIAMOS EL CLUSTERING JERÁRQUICO
            jerarquico = AgglomerativeClustering(n_clusters=k, linkage='ward')
            labels = jerarquico.fit_predict(X_subset)
            score = silhouette_score(X_subset, labels)

            if score > mejor_score_paso:
                mejor_score_paso = score
                mejor_variable_paso = var_candidata
                mejor_labels_paso = labels # Guardamos las etiquetas ganadoras

        # Consolidamos la variable ganadora de este paso
        variables_seleccionadas.append(mejor_variable_paso)
        columnas_disponibles.remove(mejor_variable_paso)

        # Calculamos N por clúster
        conteos_paso = np.bincount(mejor_labels_paso).tolist()

        historial_scores.append(mejor_score_paso)
        historial_conteos.append(conteos_paso)

        print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

    # --- PASO 3: Encontrar el pico máximo para este K ---
    indice_mejor_momento = historial_scores.index(max(historial_scores))
    score_pico = historial_scores[indice_mejor_momento]
    conteos_pico = historial_conteos[indice_mejor_momento]

    # El índice 0 equivale a 2 variables, índice 1 a 3 variables, etc.
    vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

    resultados_finales[k] = {
        'score': score_pico,
        'variables': vars_en_pico,
        'conteos': conteos_pico
    }

    # Actualizar campeón global absoluto
    if score_pico > campeon_global_score:
        campeon_global_score = score_pico
        campeon_global_k = k
        campeon_global_vars = vars_en_pico
        campeon_global_conteos = conteos_pico

print("\n" + "=" * 80)
print("🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆")
print("=" * 80)

print(f"\n🌟 EL CAMPEÓN ABSOLUTO:")
print(f"  -> K Óptimo: {campeon_global_k}")
print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
print(f"  -> Distribución de Pacientes (N): {campeon_global_conteos}")
print(f"  -> Variables óptimas ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

print("\n--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---")
for k in rango_k:
    res = resultados_finales[k]
    print(f"\nPara K={k}:")
    print(f"  -> Silhouette Score: {res['score']:.4f}")
    print(f"  -> Distribución de Pacientes (N): {res['conteos']}")
    print(f"  -> N Variables: {len(res['variables'])}")
    print(f"  -> Variables: {', '.join(res['variables'])}")

================================================================================
FORWARD SELECTION: CLUSTERING JERÁRQUICO CON TAMAÑO (N)
================================================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'trigliceridos_mmol_l') (Score: 0.5572) | Tamaños N: [1821, 98]
  -> + Variable 3: 'hemoglobina_g_dl' | Nuevo Score: 0.3603 | Tamaños N: [1650, 269]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.4333 | Tamaños N: [1820, 99]
  -> + Variable 5: 'conc_hemoglobina_media' | Nuevo Score: 0.3943 | Tamaños N: [1804, 115]
  -> + Variable 6: 'pulso' | Nuevo Score: 0.3846 | Tamaños N: [1832, 87]
  -> + Variable 7: 'creatinina_orina_umol_l' | Nuevo Score: 0.3562 | Tamaños N: [1825, 94]
  -> + Variable 8: 'peso_kg' | Nuevo Score: 0.3029 | Tamaños N: [1801, 118]
  -> + Variable 9: 'tamano_hogar' | Nuevo Score: 0.2435 | Tamaños N: [1782, 137]
  -> + Variable 10: 'edad_an' | Nuevo Score: 0.2885 | Tamaños N: [1835, 84]
  -> + Variable 11: 'plaquetas_totales' | Nuevo Score: 0.2099 | Tamaños N: [1778, 141]
  -> + Variable 12: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.2632 | Tamaños N: [1836, 83]
  -> + Variable 13: 'hdl_mmol_l' | Nuevo Score: 0.0857 | Tamaños N: [1288, 631]
  -> + Variable 14: 'largo_brazo_superior_cm' | Nuevo Score: 0.0710 | Tamaños N: [1189, 730]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'trigliceridos_mmol_l') (Score: 0.5166) | Tamaños N: [1745, 98, 76]
  -> + Variable 3: 'hemoglobina_g_dl' | Nuevo Score: 0.3271 | Tamaños N: [1400, 269, 250]
  -> + Variable 4: 'plaquetas_totales' | Nuevo Score: 0.2416 | Tamaños N: [385, 251, 1283]
  -> + Variable 5: 'peso_kg' | Nuevo Score: 0.1935 | Tamaños N: [1284, 203, 432]
  -> + Variable 6: 'largo_brazo_superior_cm' | Nuevo Score: 0.1480 | Tamaños N: [945, 778, 196]
  -> + Variable 7: 'hdl_mmol_l' | Nuevo Score: 0.1483 | Tamaños N: [1090, 196, 633]
  -> + Variable 8: 'volumen_plaquetario_medio' | Nuevo Score: 0.1463 | Tamaños N: [1150, 628, 141]
  -> + Variable 9: 'creatinina_orina_umol_l' | Nuevo Score: 0.1268 | Tamaños N: [839, 1005, 75]
  -> + Variable 10: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.1120 | Tamaños N: [1046, 729, 144]
  -> + Variable 11: 'conc_hemoglobina_media' | Nuevo Score: 0.1069 | Tamaños N: [1172, 577, 170]
  -> + Variable 12: 'edad_an' | Nuevo Score: 0.0871 | Tamaños N: [806, 1015, 98]
  -> + Variable 13: 'tamano_hogar' | Nuevo Score: 0.0789 | Tamaños N: [829, 963, 127]
  -> + Variable 14: 'pulso' | Nuevo Score: 0.0700 | Tamaños N: [1049, 730, 140]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('tamano_hogar', 'edad_an') (Score: 0.4154) | Tamaños N: [177, 457, 711, 574]
  -> + Variable 3: 'trigliceridos_mmol_l' | Nuevo Score: 0.2902 | Tamaños N: [555, 197, 617, 550]
  -> + Variable 4: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.2554 | Tamaños N: [819, 844, 187, 69]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.1907 | Tamaños N: [856, 789, 135, 139]
  -> + Variable 6: 'plaquetas_totales' | Nuevo Score: 0.1463 | Tamaños N: [779, 734, 234, 172]
  -> + Variable 7: 'hdl_mmol_l' | Nuevo Score: 0.1376 | Tamaños N: [845, 225, 716, 133]
  -> + Variable 8: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.1056 | Tamaños N: [801, 373, 647, 98]
  -> + Variable 9: 'pulso' | Nuevo Score: 0.0984 | Tamaños N: [827, 657, 326, 109]
  -> + Variable 10: 'conc_hemoglobina_media' | Nuevo Score: 0.0855 | Tamaños N: [874, 608, 124, 313]
  -> + Variable 11: 'creatinina_orina_umol_l' | Nuevo Score: 0.0760 | Tamaños N: [656, 291, 803, 169]
  -> + Variable 12: 'peso_kg' | Nuevo Score: 0.0563 | Tamaños N: [617, 585, 171, 546]
  -> + Variable 13: 'volumen_plaquetario_medio' | Nuevo Score: 0.0529 | Tamaños N: [788, 545, 500, 86]
  -> + Variable 14: 'largo_brazo_superior_cm' | Nuevo Score: 0.0463 | Tamaños N: [730, 565, 140, 484]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('tamano_hogar', 'edad_an') (Score: 0.4150) | Tamaños N: [457, 574, 711, 104, 73]
  -> + Variable 3: 'trigliceridos_mmol_l' | Nuevo Score: 0.2878 | Tamaños N: [197, 246, 617, 550, 309]
  -> + Variable 4: 'plaquetas_totales' | Nuevo Score: 0.2312 | Tamaños N: [915, 280, 442, 131, 151]
  -> + Variable 5: 'volumen_plaquetario_medio' | Nuevo Score: 0.1665 | Tamaños N: [821, 307, 388, 164, 239]
  -> + Variable 6: 'hemoglobina_g_dl' | Nuevo Score: 0.1375 | Tamaños N: [921, 290, 386, 223, 99]
  -> + Variable 7: 'hdl_mmol_l' | Nuevo Score: 0.1104 | Tamaños N: [604, 783, 127, 308, 97]
  -> + Variable 8: 'conc_hemoglobina_media' | Nuevo Score: 0.0996 | Tamaños N: [745, 694, 176, 204, 100]
  -> + Variable 9: 'largo_brazo_superior_cm' | Nuevo Score: 0.0762 | Tamaños N: [836, 247, 449, 313, 74]
  -> + Variable 10: 'ancho_distribucion_eritrocitos' | Nuevo Score: 0.0660 | Tamaños N: [441, 606, 118, 435, 319]
  -> + Variable 11: 'peso_kg' | Nuevo Score: 0.0744 | Tamaños N: [705, 316, 75, 499, 324]
  -> + Variable 12: 'creatinina_orina_umol_l' | Nuevo Score: 0.0601 | Tamaños N: [817, 510, 289, 240, 63]
  -> + Variable 13: 'pulso' | Nuevo Score: 0.0438 | Tamaños N: [566, 508, 179, 373, 293]
  -> + Variable 14: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.0483 | Tamaños N: [565, 558, 140, 484, 172]

================================================================================
🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆
================================================================================

🌟 EL CAMPEÓN ABSOLUTO:
  -> K Óptimo: 2
  -> Silhouette Score Máximo: 0.5572
  -> Distribución de Pacientes (N): [1821, 98]
  -> Variables óptimas (2): ancho_distribucion_eritrocitos, trigliceridos_mmol_l

--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---

Para K=2:
  -> Silhouette Score: 0.5572
  -> Distribución de Pacientes (N): [1821, 98]
  -> N Variables: 2
  -> Variables: ancho_distribucion_eritrocitos, trigliceridos_mmol_l

Para K=3:
  -> Silhouette Score: 0.5166
  -> Distribución de Pacientes (N): [1745, 98, 76]
  -> N Variables: 2
  -> Variables: ancho_distribucion_eritrocitos, trigliceridos_mmol_l

Para K=4:
  -> Silhouette Score: 0.4154
  -> Distribución de Pacientes (N): [177, 457, 711, 574]
  -> N Variables: 2
  -> Variables: tamano_hogar, edad_an

Para K=5:
  -> Silhouette Score: 0.4150
  -> Distribución de Pacientes (N): [457, 574, 711, 104, 73]
  -> N Variables: 2
  -> Variables: tamano_hogar, edad_an

Clustering GMM (tras transofrmar y estandarizar)

In [16]:
import numpy as np
from itertools import combinations
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score

print("=" * 80)
print("FORWARD SELECTION: GAUSSIAN MIXTURE MODEL (GMM) CON TAMAÑO (N)")
print("=" * 80)

rango_k = range(2, 6) # K=2, 3, 4, 5
max_variables = 14    # Límite máximo de variables a agrupar
columnas_totales = var_num_log_scaled.columns.tolist()

resultados_finales = {}
campeon_global_score = -1
campeon_global_k = -1
campeon_global_vars = []
campeon_global_conteos = []

for k in rango_k:
    print(f"\n[ Iniciando búsqueda para K={k} ]")

    columnas_disponibles = columnas_totales.copy()
    variables_seleccionadas = []

    # --- PASO 1: Buscar el mejor PAR inicial (La base sólida) ---
    mejor_score_par = -1
    mejor_par = ()
    mejor_labels_par = None

    # Probamos las parejas posibles
    for combo in combinations(columnas_disponibles, 2):
        X_subset = var_num_log_scaled[list(combo)]

        # INSTANCIAMOS EL GAUSSIAN MIXTURE MODEL
        # n_components es el equivalente a los clústeres en GMM
        gmm = GaussianMixture(n_components=k, random_state=42)
        labels = gmm.fit_predict(X_subset)
        score = silhouette_score(X_subset, labels)

        if score > mejor_score_par:
            mejor_score_par = score
            mejor_par = combo
            mejor_labels_par = labels # Guardamos las etiquetas ganadoras

    # Fijamos el mejor par y lo sacamos de las disponibles
    variables_seleccionadas.extend(mejor_par)
    for var in mejor_par:
        columnas_disponibles.remove(var)

    # Calculamos N por clúster
    conteos_par = np.bincount(mejor_labels_par).tolist()

    print(f"  -> Mejor par inicial: {mejor_par} (Score: {mejor_score_par:.4f}) | Tamaños N: {conteos_par}")

    # Guardamos el historial de scores y conteos
    historial_scores = [mejor_score_par]
    historial_conteos = [conteos_par]

    # --- PASO 2: Forward Selection (Añadir 1 a 1 hasta max_variables) ---
    for paso in range(3, max_variables + 1):
        mejor_score_paso = -1
        mejor_variable_paso = None
        mejor_labels_paso = None

        # Probamos a añadir cada una de las variables que quedan libres
        for var_candidata in columnas_disponibles:
            features_a_probar = variables_seleccionadas + [var_candidata]
            X_subset = var_num_log_scaled[features_a_probar]

            # INSTANCIAMOS EL GAUSSIAN MIXTURE MODEL
            gmm = GaussianMixture(n_components=k, random_state=42)
            labels = gmm.fit_predict(X_subset)
            score = silhouette_score(X_subset, labels)

            if score > mejor_score_paso:
                mejor_score_paso = score
                mejor_variable_paso = var_candidata
                mejor_labels_paso = labels # Guardamos las etiquetas ganadoras

        # Consolidamos la variable ganadora de este paso
        variables_seleccionadas.append(mejor_variable_paso)
        columnas_disponibles.remove(mejor_variable_paso)

        # Calculamos N por clúster
        conteos_paso = np.bincount(mejor_labels_paso).tolist()

        historial_scores.append(mejor_score_paso)
        historial_conteos.append(conteos_paso)

        print(f"  -> + Variable {paso}: '{mejor_variable_paso}' | Nuevo Score: {mejor_score_paso:.4f} | Tamaños N: {conteos_paso}")

    # --- PASO 3: Encontrar el pico máximo para este K ---
    indice_mejor_momento = historial_scores.index(max(historial_scores))
    score_pico = historial_scores[indice_mejor_momento]
    conteos_pico = historial_conteos[indice_mejor_momento]

    # El índice 0 equivale a 2 variables, índice 1 a 3 variables, etc.
    vars_en_pico = variables_seleccionadas[:indice_mejor_momento + 2]

    resultados_finales[k] = {
        'score': score_pico,
        'variables': vars_en_pico,
        'conteos': conteos_pico
    }

    # Actualizar campeón global absoluto
    if score_pico > campeon_global_score:
        campeon_global_score = score_pico
        campeon_global_k = k
        campeon_global_vars = vars_en_pico
        campeon_global_conteos = conteos_pico

print("\n" + "=" * 80)
print("🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆")
print("=" * 80)

print(f"\n🌟 EL CAMPEÓN ABSOLUTO:")
print(f"  -> K Óptimo: {campeon_global_k}")
print(f"  -> Silhouette Score Máximo: {campeon_global_score:.4f}")
print(f"  -> Distribución de Pacientes (N): {campeon_global_conteos}")
print(f"  -> Variables óptimas ({len(campeon_global_vars)}): {', '.join(campeon_global_vars)}")

print("\n--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---")
for k in rango_k:
    res = resultados_finales[k]
    print(f"\nPara K={k}:")
    print(f"  -> Silhouette Score: {res['score']:.4f}")
    print(f"  -> Distribución de Pacientes (N): {res['conteos']}")
    print(f"  -> N Variables: {len(res['variables'])}")
    print(f"  -> Variables: {', '.join(res['variables'])}")

================================================================================
FORWARD SELECTION: GAUSSIAN MIXTURE MODEL (GMM) CON TAMAÑO (N)
================================================================================

[ Iniciando búsqueda para K=2 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'conc_hemoglobina_media') (Score: 0.5243) | Tamaños N: [1682, 237]
  -> + Variable 3: 'hemoglobina_g_dl' | Nuevo Score: 0.4449 | Tamaños N: [1668, 251]
  -> + Variable 4: 'volumen_plaquetario_medio' | Nuevo Score: 0.3799 | Tamaños N: [1655, 264]
  -> + Variable 5: 'pulso' | Nuevo Score: 0.3260 | Tamaños N: [1654, 265]
  -> + Variable 6: 'creatinina_orina_umol_l' | Nuevo Score: 0.2845 | Tamaños N: [1655, 264]
  -> + Variable 7: 'tamano_hogar' | Nuevo Score: 0.2498 | Tamaños N: [1650, 269]
  -> + Variable 8: 'plaquetas_totales' | Nuevo Score: 0.2243 | Tamaños N: [1615, 304]
  -> + Variable 9: 'largo_brazo_superior_cm' | Nuevo Score: 0.1991 | Tamaños N: [1589, 330]
  -> + Variable 10: 'peso_kg' | Nuevo Score: 0.1869 | Tamaños N: [1546, 373]
  -> + Variable 11: 'hdl_mmol_l' | Nuevo Score: 0.1743 | Tamaños N: [1552, 367]
  -> + Variable 12: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.1565 | Tamaños N: [1549, 370]
  -> + Variable 13: 'edad_an' | Nuevo Score: 0.1373 | Tamaños N: [1525, 394]
  -> + Variable 14: 'trigliceridos_mmol_l' | Nuevo Score: 0.0823 | Tamaños N: [1216, 703]

[ Iniciando búsqueda para K=3 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'edad_an') (Score: 0.4592) | Tamaños N: [915, 844, 160]
  -> + Variable 3: 'conc_hemoglobina_media' | Nuevo Score: 0.3284 | Tamaños N: [902, 168, 849]
  -> + Variable 4: 'trigliceridos_mmol_l' | Nuevo Score: 0.2579 | Tamaños N: [919, 178, 822]
  -> + Variable 5: 'hemoglobina_g_dl' | Nuevo Score: 0.2096 | Tamaños N: [924, 200, 795]
  -> + Variable 6: 'creatinina_orina_umol_l' | Nuevo Score: 0.1720 | Tamaños N: [927, 804, 188]
  -> + Variable 7: 'plaquetas_totales' | Nuevo Score: 0.1434 | Tamaños N: [906, 793, 220]
  -> + Variable 8: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.1218 | Tamaños N: [785, 908, 226]
  -> + Variable 9: 'volumen_plaquetario_medio' | Nuevo Score: 0.1061 | Tamaños N: [789, 232, 898]
  -> + Variable 10: 'tamano_hogar' | Nuevo Score: 0.0938 | Tamaños N: [717, 981, 221]
  -> + Variable 11: 'pulso' | Nuevo Score: 0.0846 | Tamaños N: [982, 718, 219]
  -> + Variable 12: 'peso_kg' | Nuevo Score: 0.0774 | Tamaños N: [865, 277, 777]
  -> + Variable 13: 'hdl_mmol_l' | Nuevo Score: 0.0658 | Tamaños N: [748, 887, 284]
  -> + Variable 14: 'largo_brazo_superior_cm' | Nuevo Score: 0.0602 | Tamaños N: [729, 862, 328]

[ Iniciando búsqueda para K=4 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'edad_an') (Score: 0.4360) | Tamaños N: [904, 765, 192, 58]
  -> + Variable 3: 'trigliceridos_mmol_l' | Nuevo Score: 0.3414 | Tamaños N: [184, 774, 793, 168]
  -> + Variable 4: 'hemoglobina_g_dl' | Nuevo Score: 0.2623 | Tamaños N: [197, 772, 764, 186]
  -> + Variable 5: 'conc_hemoglobina_media' | Nuevo Score: 0.2067 | Tamaños N: [203, 776, 763, 177]
  -> + Variable 6: 'volumen_plaquetario_medio' | Nuevo Score: 0.1658 | Tamaños N: [771, 195, 193, 760]
  -> + Variable 7: 'tamano_hogar' | Nuevo Score: 0.1371 | Tamaños N: [267, 673, 783, 196]
  -> + Variable 8: 'hdl_mmol_l' | Nuevo Score: 0.1147 | Tamaños N: [786, 200, 666, 267]
  -> + Variable 9: 'pulso' | Nuevo Score: 0.0997 | Tamaños N: [830, 181, 652, 256]
  -> + Variable 10: 'plaquetas_totales' | Nuevo Score: 0.0868 | Tamaños N: [272, 187, 655, 805]
  -> + Variable 11: 'largo_brazo_superior_cm' | Nuevo Score: 0.0771 | Tamaños N: [765, 659, 294, 201]
  -> + Variable 12: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.0681 | Tamaños N: [768, 649, 300, 202]
  -> + Variable 13: 'creatinina_orina_umol_l' | Nuevo Score: 0.0509 | Tamaños N: [738, 635, 178, 368]
  -> + Variable 14: 'peso_kg' | Nuevo Score: 0.0459 | Tamaños N: [502, 681, 466, 270]

[ Iniciando búsqueda para K=5 ]
  -> Mejor par inicial: ('ancho_distribucion_eritrocitos', 'tamano_hogar') (Score: 0.3919) | Tamaños N: [513, 72, 226, 873, 235]
  -> + Variable 3: 'creatinina_orina_umol_l' | Nuevo Score: 0.2913 | Tamaños N: [716, 245, 370, 507, 81]
  -> + Variable 4: 'edad_an' | Nuevo Score: 0.2412 | Tamaños N: [346, 674, 154, 518, 227]
  -> + Variable 5: 'plaquetas_totales' | Nuevo Score: 0.1884 | Tamaños N: [360, 678, 505, 228, 148]
  -> + Variable 6: 'hemoglobina_g_dl' | Nuevo Score: 0.1546 | Tamaños N: [345, 672, 220, 504, 178]
  -> + Variable 7: 'hdl_mmol_l' | Nuevo Score: 0.1296 | Tamaños N: [351, 632, 484, 185, 267]
  -> + Variable 8: 'largo_brazo_superior_cm' | Nuevo Score: 0.1026 | Tamaños N: [414, 498, 254, 597, 156]
  -> + Variable 9: 'trigliceridos_mmol_l' | Nuevo Score: 0.0915 | Tamaños N: [212, 350, 176, 588, 593]
  -> + Variable 10: 'conc_hemoglobina_media' | Nuevo Score: 0.0823 | Tamaños N: [195, 584, 356, 605, 179]
  -> + Variable 11: 'volumen_plaquetario_medio' | Nuevo Score: 0.0728 | Tamaños N: [256, 581, 559, 348, 175]
  -> + Variable 12: 'mercurio_sangre_nmol_l' | Nuevo Score: 0.0597 | Tamaños N: [213, 595, 560, 382, 169]
  -> + Variable 13: 'peso_kg' | Nuevo Score: 0.0503 | Tamaños N: [249, 420, 237, 575, 438]
  -> + Variable 14: 'pulso' | Nuevo Score: 0.0284 | Tamaños N: [272, 575, 367, 526, 179]

================================================================================
🏆 RESULTADOS FINALES: FORWARD SELECTION 🏆
================================================================================

🌟 EL CAMPEÓN ABSOLUTO:
  -> K Óptimo: 2
  -> Silhouette Score Máximo: 0.5243
  -> Distribución de Pacientes (N): [1682, 237]
  -> Variables óptimas (2): ancho_distribucion_eritrocitos, conc_hemoglobina_media

--- MEJOR COMBINACIÓN ENCONTRADA PARA CADA K ---

Para K=2:
  -> Silhouette Score: 0.5243
  -> Distribución de Pacientes (N): [1682, 237]
  -> N Variables: 2
  -> Variables: ancho_distribucion_eritrocitos, conc_hemoglobina_media

Para K=3:
  -> Silhouette Score: 0.4592
  -> Distribución de Pacientes (N): [915, 844, 160]
  -> N Variables: 2
  -> Variables: ancho_distribucion_eritrocitos, edad_an

Para K=4:
  -> Silhouette Score: 0.4360
  -> Distribución de Pacientes (N): [904, 765, 192, 58]
  -> N Variables: 2
  -> Variables: ancho_distribucion_eritrocitos, edad_an

Para K=5:
  -> Silhouette Score: 0.3919
  -> Distribución de Pacientes (N): [513, 72, 226, 873, 235]
  -> N Variables: 2
  -> Variables: ancho_distribucion_eritrocitos, tamano_hogar